<?php if(isset($poll)) : ?>
    <script>
        function validatePollAnswerIsSelected()
        {
            var options = $$('input.poll_vote');
            for( i in options ) {
                if( options[i].checked == true ) {
                    return true;
                }
            }
            return false;
        }
    </script>
    <div class="block block-poll">
        <div class="block-title">
            <h3><?php echo $this->__('Community Poll') ?></h3>
        </div>
        <form id="pollForm" action="<?php echo $action ?>" method="post" onsubmit="return validatePollAnswerIsSelected();">
            <div class="block-content">
                <p class="block-subtitle"><?php echo $this->htmlEscape($poll->getPollTitle()); ?></p>
                <?php if( $poll_answers ): ?>
                    <ul id="poll-answers">
                        <?php foreach( $poll_answers as $answer ): ?>
                            <li>
                                <label for="vote_<?php echo $answer->getId() ?>">
                                    <input type="radio" name="vote" class="radio poll_vote" id="vote_<?php echo $answer->getId() ?>" value="<?php echo $answer->getAnswerId() ?>" />
                                    <?php echo $this->htmlEscape($answer->getAnswerTitle()) ?>
                                </label>
                            </li>
                        <?php endforeach; ?>
                    </ul>
                <?php endif; ?>
                <div class="actions">
                    <button type="submit" title="<?php echo $this->__('Vote') ?>" class="button"><span><?php echo $this->__('Vote') ?></span></button>
                </div>
            </div>
        </form>
    </div>
<?php endif; ?>
