<?php
/**
 * Shoping cart sidebar
 *
 * @see Mage_Checkout_Block_Cart_Sidebar
 */

$_cartQty       = $this->getSummaryCount() ? $this->getSummaryCount() : 0;
$_items         = $this->getRecentItems();
$_continueLink  = $this->isPossibleOnepageCheckout() ? $this->getCheckoutUrl() : $this->getUrl('checkout/cart');
?>
<div class="header__cart">
    <a href="<?php echo $_continueLink; ?>" class="button"><?php echo $this->__('Cart (%s)', $_cartQty); ?></a>

    <?php if(count($_items)) : ?>
        <div class="header__cart__content">
            <h3><?php echo $this->__('Recently added item(s)') ?></h3>
            <ol>
                <?php foreach($_items as $_item) : ?>
                    <?php echo $this->getItemHtml($_item); ?>
                <?php endforeach; ?>
            </ol>

            <div class="cart__subtotal">
                <?php if(!$this->canApplyMsrp()) : ?>
                    <span><?php echo $this->__('Cart Subtotal:') ?></span>
                    <?php echo Mage::helper('checkout')->formatPrice($this->getSubtotal()) ?>
                    <?php if($_subtotalInclTax = $this->getSubtotalInclTax()) : ?>
                        (<?php echo Mage::helper('checkout')->formatPrice($_subtotalInclTax) ?> <?php echo Mage::helper('tax')->getIncExcText(true) ?>)
                    <?php endif; ?>
                <?php endif; ?>
            </div>

            <?php if($_cartQty && $this->isPossibleOnepageCheckout()) : ?>
                <div class="cart__actions">
                    <a class="button" title="<?php echo $this->__('Checkout') ?>" href="<?php echo $this->getCheckoutUrl(); ?>"><?php echo $this->__('Checkout') ?></a>
                </div>
            <?php endif; ?>
        </div>
    <?php endif; ?>
</div>