<?php
/**
 * Edit customer address template
 *
 * @see Mage_Customer_Block_Address_Edit
 */
?>
<?php if($this->getTitle()) : ?>
    <div class="page-title">
        <h1><?php echo $this->getTitle() ?></h1>
    </div>
<?php endif; ?>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<form action="<?php echo $this->getSaveUrl() ?>" method="post" id="form-validate" enctype="multipart/form-data">
    <h2 class="legend"><?php echo $this->__('Contact Information') ?></h2>
    <?php echo $this->getBlockHtml('formkey'); ?>
    <input type="hidden" name="success_url" value="<?php echo $this->getSuccessUrl() ?>" />
    <input type="hidden" name="error_url" value="<?php echo $this->getErrorUrl() ?>" />

    <?php echo $this->getNameBlockHtml() ?>
    <label for="company"><?php echo $this->__('Company') ?></label>
        <input type="text" name="company" id="company" title="<?php echo $this->__('Company') ?>" value="<?php echo $this->escapeHtml($this->getAddress()->getCompany()) ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('company') ?>" />
    <label for="telephone" class="required"><?php echo $this->__('Telephone') ?> <em>*</em></label>
        <input type="text" name="telephone" value="<?php echo $this->escapeHtml($this->getAddress()->getTelephone()) ?>" title="<?php echo $this->__('Telephone') ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('telephone') ?>" id="telephone" />
    <label for="fax"><?php echo $this->__('Fax') ?></label>
        <input type="text" name="fax" id="fax" title="<?php echo $this->__('Fax') ?>" value="<?php echo $this->escapeHtml($this->getAddress()->getFax()) ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('fax') ?>" />

    <h2 class="legend"><?php echo $this->__('Address') ?></h2>
    <?php $_streetValidationClass = $this->helper('customer/address')->getAttributeValidationClass('street'); ?>
    <label for="street_1" class="required"><?php echo $this->__('Street Address') ?> <em>*</em></label>
        <input type="text" name="street[]" value="<?php echo $this->escapeHtml($this->getAddress()->getStreet(1)) ?>" title="<?php echo $this->__('Street Address') ?>" id="street_1" class="input-text <?php echo $_streetValidationClass ?>" />
    <?php $_streetValidationClass = trim(str_replace('required-entry', '', $_streetValidationClass)); ?>
    <?php for($_i = 2, $_n = $this->helper('customer/address')->getStreetLines(); $_i <= $_n; $_i++) : ?>
        <div>
            <input type="text" name="street[]" value="<?php echo $this->escapeHtml($this->getAddress()->getStreet($_i)) ?>" title="<?php echo $this->__('Street Address %s', $_i) ?>" id="street_<?php echo $_i ?>" class="input-text <?php echo $_streetValidationClass ?>" />
        </div>
    <?php endfor; ?>

    <?php if ($this->helper('customer/address')->isVatAttributeVisible()) : ?>
        <label for="vat_id"><?php echo $this->__('VAT Number') ?></label>
            <input type="text" name="vat_id" value="<?php echo $this->escapeHtml($this->getAddress()->getVatId()) ?>" title="<?php echo $this->__('VAT Number') ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('vat_id') ?>" id="vat_id" />
    <?php endif; ?>

    <label for="city" class="required"><?php echo $this->__('City') ?> <em>*</em></label>
        <input type="text" name="city" value="<?php echo $this->escapeHtml($this->getAddress()->getCity()) ?>" title="<?php echo $this->__('City') ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('city') ?>" id="city" />

    <div class="hidden">
        <label for="region_id" class="required"><?php echo $this->__('State/Province') ?> <em>*</em></label>
        <select id="region_id" name="region_id" title="<?php echo $this->__('State/Province') ?>" class="validate-select" style="display:none;">
           <option value=""><?php echo $this->__('Please select region, state or province') ?></option>
        </select>
        <script>
            $('region_id').setAttribute('defaultValue',  "<?php echo $this->getAddress()->getRegionId() ?>");
        </script>
    </div>
    <input type="text" id="region" name="region" value="<?php echo $this->escapeHtml($this->getAddress()->getRegion()) ?>"  title="<?php echo $this->__('State/Province') ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('region') ?>" />

    <label for="zip" class="required"><?php echo $this->__('Zip/Postal Code') ?> <em>*</em></label>
        <input type="text" name="postcode" value="<?php echo $this->escapeHtml($this->getAddress()->getPostcode()) ?>" title="<?php echo $this->__('Zip/Postal Code') ?>" id="zip" class="input-text validate-zip-international <?php echo $this->helper('customer/address')->getAttributeValidationClass('postcode') ?>" />

    <label for="country" class="required"><?php echo $this->__('Country') ?> <em>*</em></label>
        <?php echo $this->getCountryHtmlSelect(); ?>

    <?php if($userDefinedAttributes = $this->getLayout()->getBlock('customer_form_user_attributes')) : ?>
        <?php echo $userDefinedAttributes->setEntity($this->getAddress())->setShowContainer(false)->toHtml(); ?>
    <?php endif;?>
    <?php if($this->isDefaultBilling() || $this->canSetAsDefaultBilling()) : ?>
        <?php if($this->isDefaultBilling()) : ?>
            <p><?php echo $this->__('Default Billing Address') ?></p>
        <?php elseif($this->canSetAsDefaultBilling()) : ?>
            <input type="checkbox"
                id="primary_billing"
                name="default_billing"
                value="1" />
            <label for="primary_billing"><?php echo $this->__('Use as my default billing address') ?></label>
        <?php endif; ?>
    <?php endif; ?>
    <?php if($this->isDefaultShipping() || $this->canSetAsDefaultShipping()) : ?>
        <?php if($this->isDefaultShipping()) : ?>
            <p><?php echo $this->__('Default Shipping Address') ?></p>
        <?php elseif($this->canSetAsDefaultShipping()) : ?>
            <input type="checkbox"
                id="primary_shipping"
                name="default_shipping"
                value="1" />
            <label for="primary_shipping"><?php echo $this->__('Use as my default shipping address') ?></label>
        <?php endif; ?>
    <?php endif; ?>

    <?php if(!$this->isDefaultBilling() && !$this->canSetAsDefaultBilling()) : ?>
        <input type="hidden" name="default_billing" value="1" />
    <?php endif; ?>
    <?php if(!$this->isDefaultShipping() && !$this->canSetAsDefaultShipping()) : ?>
        <input type="hidden" name="default_shipping" value="1" />
    <?php endif; ?>

    <p>
        <button type="submit" class="button" title="<?php echo $this->__('Save Address') ?>"><span><?php echo $this->__('Save Address') ?></span></button>
        <?php echo $this->__('or'); ?>
        <a href="<?php echo $this->escapeUrl($this->getBackUrl()) ?>"><?php echo $this->__('Go back') ?></a>
    </p>
</form>
<script>
    document.observe('dom:loaded', function() {
        var dataForm = new VarienForm('form-validate', true);
        new RegionUpdater('country', 'region', 'region_id', <?php echo $this->helper('directory')->getRegionJson() ?>, undefined, 'zip');
    });
</script>