<?php
/**
 * Pager template
 *
 * @see Mage_Page_Block_Html_Pager
 */

if($this->getCollection()->getSize() && $this->getLastPageNum()>1) : ?>
    <nav class="pages">
        <ol>
            <?php if(!$this->isFirstPage()) : ?>
                <li class="previous<?php if(!$this->getAnchorTextForPrevious()): ?> i-previous<?php endif;?>">
                    <a href="<?php echo $this->getPreviousPageUrl() ?>"
                        title="<?php echo $this->__('Previous page') ?>">
                        <?php echo $this->__('Previous') ?></a>
                </li>
            <?php endif;?>

            <?php if($this->canShowFirst()) : ?>
                <li class="first"><a href="<?php echo $this->getFirstPageUrl() ?>">1</a></li>
            <?php endif; ?>

            <?php if($this->canShowPreviousJump()) : ?>
                <li class="previous_jump"><a href="<?php echo $this->getPreviousJumpUrl() ?>">&#x2026;</a></li>
            <?php endif; ?>

            <?php foreach($this->getFramePages() as $_page) : ?>
                <?php if($this->isPageCurrent($_page)) : ?>
                    <li class="current"><?php echo $_page ?></li>
                <?php else: ?>
                    <li><a href="<?php echo $this->getPageUrl($_page) ?>"><?php echo $_page ?></a></li>
                <?php endif;?>
            <?php endforeach;?>

            <?php if($this->canShowNextJump()) : ?>
                <li class="next_jump"><a href="<?php echo $this->getNextJumpUrl() ?>">&#x2026;</a></li>
            <?php endif;?>

            <?php if($this->canShowLast()) : ?>
                <li class="last"><a href="<?php echo $this->getLastPageUrl() ?>"><?php echo $this->getLastPageNum() ?></a></li>
            <?php endif;?>

            <?php if(!$this->isLastPage()) : ?>
                <li class="next<?php if(!$this->getAnchorTextForNext()): ?> i-next<?php endif; ?>">
                    <a href="<?php echo $this->getNextPageUrl() ?>"
                        title="<?php echo $this->__('Next page') ?>">
                        <?php echo $this->__('Next') ?></a>
                </li>
            <?php endif;?>
        </ol>
    </nav>
<?php endif ?>