<div class="info-box">
    <h3 class="box-title"><?php echo $this->__('Contact Information') ?></h3>
    <p class="box-content">
        <?php echo $this->htmlEscape($this->getCustomer()->getName()) ?><br />
        <?php echo $this->htmlEscape($this->getCustomer()->getEmail()) ?><br />
    </p>
    <p class="actions">
        <a href="<?php echo $this->getUrl('customer/account/edit') ?>"><?php echo $this->__('Edit') ?></a>
        <a href="<?php echo $this->getChangePasswordUrl() ?>"><?php echo $this->__('Change Password') ?></a>
    </p>
</div>

<?php if($this->isNewsletterEnabled()) : ?>
    <div class="info-box">
        <h3 class="box-title"><?php echo $this->__('Newsletters') ?></h3>
        <p class="box-content">
            <?php if( $this->getIsSubscribed() ): ?>
                <?php echo $this->__("You are currently subscribed to 'General Subscription'.") ?>
            <?php else: ?>
                <?php echo $this->__('You are currently not subscribed to any newsletter.') ?>
            <?php endif; ?>
        </p>
        <p class="actions">
            <a href="<?php echo $this->getUrl('newsletter/manage') ?>"><?php echo $this->__('Edit') ?></a>
        </p>
    </div>
    <?php /* Extensions placeholder */ ?>
    <?php echo $this->getChildHtml('customer.account.dashboard.info.extra')?>
<?php endif; ?>