<?php if ($this->hasItems()): ?>
    <div class="box-collateral box-up-sell">
        <div class="box-title">
            <h2><?php echo $this->__('You may also be interested in the following product(s)') ?></h2>
        </div>
        <ul class="products-grid">
            <?php foreach($this->getItemCollection() as $_item) : ?>
                <li class="item">
                    <?php echo $this->getChild('catalog.product.upsell.item')->setItem($_item)->toHtml(); ?>
                </li>
            <?php endforeach; ?>
        </ul>
    </div>
<?php endif ?>