<?php
/**
 * Should match checkout/cart/item/configure/updatecart.phtml
 *
 */

$_product = $this->getProduct();
?>
<?php $buttonTitle = $this->__('Add to Cart'); ?>
<?php if($_product->isSaleable()): ?>
    <div class="add-to-cart">
        <?php if(!$_product->isGrouped()): ?>
            <input name="qty" id="qty" maxlength="3" value="<?php echo $this->getProductDefaultQty() * 1 ?>" title="<?php echo $this->__('Qty') ?>" class="qty" />
        <?php endif; ?>
        <button title="<?php echo $buttonTitle ?>" id="addToCartButton" class="primary"><span><?php echo $buttonTitle ?></span></button>
        <?php echo $this->getChildHtml('', true, true) ?>
    </div>
<?php endif; ?>