<?php
/**
 * Product additional attributes template
 *
 * @see Mage_Catalog_Block_Product_View_Attributes
 */

$_helper  = $this->helper('catalog/output');
$_product = $this->getProduct();
if($_additional = $this->getAdditionalData()) : ?>
    <dl class="product-attributes">
        <?php foreach($_additional as $_data) : ?>
            <dt><?php echo $this->htmlEscape($this->__($_data['label'])) ?></dt>
                <dd class="<?php echo $_data['code']; ?>"><?php echo $_helper->productAttribute($_product, $_data['value'], $_data['code']) ?></dd>
        <?php endforeach; ?>
    </dl>
<?php endif; ?>