<?php
/**
 * Product media data template
 *
 * @see Mage_Catalog_Block_Product_View_Media
 */

$_product = $this->getProduct();
$_helper  = $this->helper('catalog/output');
$_img     = '<img itemprop="image"
    src="'.$this->helper('catalog/image')->init($_product, 'image')->resize(512).'"
    alt="'.$this->htmlEscape($this->getImageLabel()).'"
    title="'.$this->htmlEscape($this->getImageLabel()).'" />';
?>

<div class="product-media">
    <p class="product-image"><?php echo $_helper->productAttribute($_product, $_img, 'image'); ?></p>

    <?php if (count($this->getGalleryImages()) > 0): ?>
        <div class="more-views">
            <h2><?php echo $this->__('More Views') ?></h2>
            <ul>
                <?php foreach($this->getGalleryImages() as $_image) : ?>
                    <li>
                        <a href="<?php echo $this->helper('catalog/image')->init($this->getProduct(), 'image', $_image->getFile()); ?>"
                            title="<?php echo $this->htmlEscape($_image->getLabel()) ?>">
                            <img src="<?php echo $this->helper('catalog/image')->init($this->getProduct(), 'thumbnail', $_image->getFile())->resize(64); ?>"
                                 alt="<?php echo $this->htmlEscape($_product->getName()) ?>"
                                 title="<?php echo $this->htmlEscape($_product->getName()) ?>" /><!--$_image->getLabel()-->
                        </a>
                    </li>
                <?php endforeach; ?>
            </ul>
        </div>
    <?php endif; ?>
</div>