<div class="page-title">
    <h1><?php echo $this->__('Share Your Wishlist') ?></h1>
</div>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<form action="<?php echo $this->getSendUrl() ?>" id="form-validate" method="post">
    <?php echo $this->getBlockHtml('formkey')?>
    <h2><?php echo $this->__('Sharing Information') ?></h2>

    <label for="email_address" class="required"><?php echo $this->__('Email addresses, separated by commas') ?> <em>*</em></label>
    <textarea name="emails" cols="60" rows="2" id="email_address" class="validate-emails required-entry"><?php echo $this->getEnteredData('emails') ?></textarea>

    <label for="message"><?php echo $this->__('Message') ?></label>
    <textarea id="message" name="message" cols="60" rows="5"><?php echo $this->getEnteredData('message') ?></textarea>

    <?php if($this->helper('wishlist')->isRssAllow()) : ?>
        <input type="checkbox"
            name="rss_url"
            id="rss_url"
            value="1"
            title="<?php echo $this->__('Check this checkbox if you want to add a link to an rss feed to your wishlist.') ?>" />
        <label for="rss_url"><?php echo $this->__('Check this checkbox if you want to add a link to an rss feed to your wishlist.') ?></label>
    <?php endif; ?>

    <p class="required"><small><?php echo $this->__('* Required Fields') ?></small></p>
    <p class="back-link"><a href="<?php echo $this->getBackUrl(); ?>"><small>&laquo; </small><?php echo $this->__('Back')?></a></p>
    <button type="submit" title="<?php echo $this->__('Share Wishlist') ?>" class="button primary"><span><?php echo $this->__('Share Wishlist') ?></span></button>
</form>

<script>
    document.observe('dom:loaded', function() {
        Validation.addAllThese([
            ['validate-emails', '<?php echo $this->__('Please enter a valid email addresses, separated by commas. For example johndoe@domain.com, johnsmith@domain.com.') ?>', function (v) {
            if(Validation.get('IsEmpty').test(v)) {
                return true;
            }

            var valid_regexp = /^[a-z0-9\._-]{1,30}@([a-z0-9_-]{1,30}\.){1,5}[a-z]{2,4}$/i;
            var emails = v.split(',');
            for (var i=0; i<emails.length; i++) {
                if(!valid_regexp.test(emails[i].strip())) {
                    return false;
                }
            }

            return true;
            }]
        ]);
        var dataForm = new VarienForm('form-validate', true);
    });
</script>