<?php
/** @var
 * $this Mage_Bundle_Block_Catalog_Product_View_Type_Bundle
 *
 */

$_product = $this->getProduct();
?>

<?php if($_product->isSaleable()) : ?>
    <script>
        var bundle = new Product.Bundle(<?php echo $this->getJsonConfig() ?>);
    </script>
<?php endif; ?>
<?php if ($this->displayProductStockStatus()): ?>
    <?php if ($_product->isAvailable()): ?>
        <p class="availability in-stock"><?php echo $this->helper('catalog')->__('Availability:') ?> <span><?php echo $this->helper('catalog')->__('In stock') ?></span></p>
    <?php else: ?>
        <p class="availability out-of-stock"><?php echo $this->helper('catalog')->__('Availability:') ?> <span><?php echo $this->helper('catalog')->__('Out of stock') ?></span></p>
    <?php endif; ?>
<?php endif; ?>
<div class="price-box-bundle">
    <?php echo $this->getPriceHtml($_product); ?>
</div>
<?php echo $this->getChildHtml('bundle_prices'); ?>