<ul class="checkout__payment-methods sp-methods" id="checkout-payment-method-load">
    <?php
        $methods = $this->getMethods();
        $oneMethod = count($methods) <= 1;
    ?>
    <?php foreach ($methods as $_method) : $_code = $_method->getCode(); ?>
        <li class="payment__method">
            <label for="p_method_<?php echo $_code ?>">
                <?php if(!$oneMethod): ?>
                    <input id="p_method_<?php echo $_code ?>" value="<?php echo $_code ?>" type="radio" name="payment[method]" title="<?php echo $this->htmlEscape($_method->getTitle()) ?>" onclick="payment.switchMethod('<?php echo $_code ?>')"<?php if($this->getSelectedMethodCode()==$_code): ?> checked="checked"<?php endif; ?> class="radio" />
                <?php else : ?>
                    <input id="p_method_<?php echo $_code ?>" value="<?php echo $_code ?>" type="hidden" name="payment[method]" />
                    <?php $oneMethod = $_code; ?>
                <?php endif; ?>
                <?php echo $this->escapeHtml($this->getMethodTitle($_method)); ?>
                <?php echo $_code === 'paypal_standard' ? $this->__('PayPal') : ''; ?>
            </label>
            <?php echo $this->getMethodLabelAfterHtml($_method) ?>
            <?php if ($html = $this->getPaymentMethodFormHtml($_method)) : ?>
                <div class="payment__details">
                    <?php echo $html; ?>
                </div>
            <?php endif; ?>
        </li>
    <?php endforeach; ?>
</ul>
<?php echo $this->getChildChildHtml('additional'); ?>
<script>
    <?php echo $this->getChildChildHtml('scripts'); ?>
    document.observe('dom:loaded', function() {
        payment.init();
        <?php if (is_string($oneMethod)): ?>
        payment.switchMethod('<?php echo $oneMethod ?>');
        <?php endif; ?>
    });
</script>