<form action="<?php echo $this->getFormActionUrl() ?>" method="post" id="newsletter-validate-detail">
    <div class="form-subscribe">
    <div class="form-subscribe-header">
        <label for="newsletter"><?php echo $this->__('Sign Up for Our Newsletter:') ?></label>
    </div>
    <input name="email"
        type="text"
        id="newsletter"
        value="<?php echo $this->__('Enter your email address') ?>"
        placeholder="<?php echo $this->__('Enter your email address') ?>"
        class="input-text required-entry validate-email" />
    <button type="submit" class="button" title="<?php echo $this->__('Subscribe') ?>"><span><?php echo $this->__('Subscribe') ?></span></button>
</form>
<script>
    document.observe('dom:loaded', function() {
        new VarienForm('newsletter-validate-detail');
    });
</script>
