<div class="page-title">
    <h1><?php echo $this->__('Edit Account Information') ?></h1>
</div>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>

<form action="<?php echo $this->getUrl('customer/account/editPost') ?>"
    method="post"
    id="form-validate"
    enctype="multipart/form-data"
    class="form--layout">
    <?php echo $this->getBlockHtml('formkey'); ?>

    <ul>
        <?php echo $this->getLayout()->createBlock('customer/widget_name')->setObject($this->getCustomer())->toHtml() ?>

        <li>
            <label for="email" class="required"><?php echo $this->__('Email Address') ?></label>
            <input type="email"
                name="email"
                id="email"
                value="<?php echo $this->htmlEscape($this->getCustomer()->getEmail()) ?>"
                title="<?php echo $this->__('Email Address') ?>"
                class="input-text required-entry validate-email" />
        </li>


        <?php
        $_dob    = $this->getLayout()->createBlock('customer/widget_dob');
        $_taxvat = $this->getLayout()->createBlock('customer/widget_taxvat');
        $_gender = $this->getLayout()->createBlock('customer/widget_gender'); ?>
        <?php if($_dob->isEnabled() || $_taxvat->isEnabled() || $_gender->isEnabled()) : ?>
            <?php if ($_dob->isEnabled()): ?>
                <li><?php echo $_dob->setDate($this->getCustomer()->getDob())->toHtml() ?></li>
            <?php endif ?>
            <?php if ($_taxvat->isEnabled()): ?>
                <li><?php echo $_taxvat->setTaxvat($this->getCustomer()->getTaxvat())->toHtml() ?></li>
            <?php endif ?>
            <?php if ($_gender->isEnabled()): ?>
                <li><?php echo $_gender->setGender($this->getCustomer()->getGender())->toHtml() ?></li>
            <?php endif ?>
        <?php endif; ?>

        <li class="field--checkbox">
            <input type="checkbox"
            name="change_password"
            id="change_password"
            value="1"
            title="<?php echo $this->__('Change Password') ?>"
            <?php if($this->getCustomer()->getChangePassword()==1) : ?>
                checked="checked"
            <?php endif; ?> />
            <label for="change_password"><?php echo $this->__('Change Password') ?></label>
        </li>
    </ul>

    <?php $userDefinedAttributes = $this->getLayout()->getBlock('customer_form_user_attributes'); ?>
    <?php if($userDefinedAttributes) : ?>
        <?php echo $userDefinedAttributes->setEntity($this->getCustomer())->toHtml(); ?>
    <?php endif; ?>
    <ul style="display:none">
        <li>
            <label for="current_password"><?php echo $this->__('Current Password') ?></label>
            <input type="password" name="current_password" id="current_password" />
        </li>

        <li>
            <label for="password"><?php echo $this->__('New Password') ?></label>
            <input type="password" class="validate-password" name="password" id="password" />
        </li>

        <li>
            <label for="confirmation"><?php echo $this->__('Confirm New Password') ?></label>
            <input type="password" class="validate-cpassword" name="confirmation" id="confirmation" />
        </li>
    </ul>

    <button type="submit" class="button" title="<?php echo $this->__('Save') ?>"><span><?php echo $this->__('Save Account') ?></span></button>
</form>
<script>
    document.observe('dom:loaded', function() {
        var dataForm = new VarienForm('form-validate', true);
        function setPasswordForm(arg) {
            var passwordForm = $('current_password').up(1);
            if(arg) {
                passwordForm.show();
                $('current_password').addClassName('required-entry');
                $('password').addClassName('required-entry');
                $('confirmation').addClassName('required-entry');

            }
            else {
                passwordForm.hide();
                $('current_password').removeClassName('required-entry');
                $('password').removeClassName('required-entry');
                $('confirmation').removeClassName('required-entry');
            }
        }
        <?php if($this->getCustomer()->getChangePassword()): ?>
            setPasswordForm(true);
        <?php endif; ?>

        if($('change_password')) {
            $('change_password').observe('click', function(event) {
                setPasswordForm(this.checked);
            });
        }
    });
</script>