<article>
    <header class="page-title">
        <h1><?php echo $this->__('Forgot Your Password?') ?></h1>
    </header>
    <p><?php echo $this->__('Please enter your email below and we will send you a new password.') ?></p>
    <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
    <form action="<?php echo $this->getUrl('*/*/forgotpasswordpost') ?>" method="post" id="form-validate">
        <label for="email_address" class="required"><?php echo $this->__('Email Address') ?> <em>*</em></label>
        <input type="text" name="email" alt="email" id="email_address" class="input-text required-entry validate-email" value="<?php echo $this->htmlEscape($this->getEmailValue()) ?>" />

        <p>
            <button type="submit" title="<?php echo $this->__('Submit') ?>" class="primary"><span><?php echo $this->__('Get a new password') ?></span></button>
            <?php echo $this->__('or'); ?>
            <a href="<?php echo $this->helper('customer')->getLoginUrl() ?>"><?php echo $this->__('Back to Login') ?></a>
        </p>
    </form>
</article>
<script>
    document.observe('dom:loaded', function() {
        var dataForm = new VarienForm('form-validate', true);
    });
</script>