<article>
    <header class="page-title">
        <h1><?php echo $this->__('Reset Password') ?></h1>
    </header>
    <p><?php echo $this->__('Enter your email below and we will help reset your password.') ?></p>
    <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
    <form action="<?php echo $this->getUrl('*/*/forgotpasswordpost') ?>" method="post" id="form-validate">
        <label for="email_address" class="required"><?php echo $this->__('Email Address') ?></label>
        <input type="text" name="email" alt="email" id="email_address" class="input-text required-entry validate-email" value="<?php echo $this->htmlEscape($this->getEmailValue()) ?>" />

        <button type="submit" title="<?php echo $this->__('Submit') ?>" class="primary"><span><?php echo $this->__('Send Link') ?></span></button>
    </form>
</article>
<script>
    document.observe('dom:loaded', function() {
        var dataForm = new VarienForm('form-validate', true);
    });
</script>