<div class="page-title">
    <h1><?php echo $this->__('Newsletter Subscription') ?></h1>
</div>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<?php echo $this->getChildHtml('form_before')?>
<form action="<?php echo $this->getAction() ?>" method="post" id="form-validate">
    <?php echo $this->getBlockHtml('formkey')?>

    <p>
        <input type="checkbox"
            name="is_subscribed"
            id="subscription"
            value="1"
            title="<?php echo $this->__('General Subscription') ?>"
            <?php if($this->getIsSubscribed()) : ?>
                checked="checked"
            <?php endif; ?> />
        <label for="subscription"><?php echo $this->__('General Subscription') ?></label>
    </p>

    <?php /* Extensions placeholder */ ?>
    <?php echo $this->getChildHtml('customer.form.newsletter.extra')?>
    <p>
        <button type="submit" class="button" title="<?php echo $this->__('Save') ?>"><span><?php echo $this->__('Save') ?></span></button>
    </p>
</form>
<?php /* Extensions placeholder */ ?>
<?php echo $this->getChildHtml('customer.form.newsletter.extra2')?>
<script>
    document.observe('dom:loaded', function() {
        var dataForm = new VarienForm('form-validate', true);
    });
</script>
