<script>
    var lifetime;
    var expireAt;

	document.observe('dom:loaded', function() {
	    lifetime = <?php echo Mage::helper('pagecache')->getNoCacheCookieLifetime(); ?>;
	    expireAt = Mage.Cookies.expires;

	    if (lifetime > 0) {
	        expireAt = new Date();
	        expireAt.setTime(expireAt.getTime() + lifetime * 1000);
	    }

	    Mage.Cookies.set('<?php echo Mage_PageCache_Helper_Data::NO_CACHE_COOKIE; ?>', 1, expireAt);
	});
</script>