<?php
$_product = $this->getProduct();
$_compareUrl = $this->helper('catalog/product_compare')->getAddUrl($_product);

if($this->helper('wishlist')->isAllow() || $_compareUrl) : ?>
    <ul class="add-to-links">
        <?php if($this->helper('wishlist')->isAllow()) : ?>
            <?php $_wishlistSubmitUrl = $this->helper('wishlist')->getAddUrl($_product); ?>
            <li><a href="<?php echo $_wishlistSubmitUrl ?>" id="addToWishlistButton" class="link-wishlist"><?php echo $this->__('Add to Wishlist') ?></a></li>
        <?php endif; ?>
        <?php if($_compareUrl) : ?>
            <li><a href="<?php echo $_compareUrl ?>" class="link-compare"><?php echo $this->__('Add to Compare') ?></a></li>
        <?php endif; ?>
    </ul>
<?php endif; ?>