<?php
/**
 * Should match catalog/product/view/addtocart.phtml
 *
 */

$_product = $this->getProduct();
?>
<?php $buttonTitle = $this->__('Update Cart'); ?>
<?php if($_product->isSaleable()): ?>
    <div class="add-to-cart">
        <?php if(!$_product->isGrouped()): ?>
            <label for="qty"><?php echo $this->__('Qty:') ?></label>
            <input type="text" name="qty" id="qty" maxlength="12" value="<?php echo $this->getProductDefaultQty() * 1 ?>" title="<?php echo $this->__('Qty') ?>" class="input-text qty" />
        <?php endif; ?>
        <button type="button" title="<?php echo $buttonTitle ?>" id="addToCartButton" class="button btn-cart"><span><?php echo $buttonTitle ?></span></button>
        <?php echo $this->getChildHtml('', true, true) ?>
    </div>
<?php endif; ?>
