<?php
/**
 * Category layered navigation
 *
 * @deprecated since 1.12.0.0
 */
?>
<?php if($this->canShowBlock()) : ?>
    <div class="block block-layered-nav">
        <div class="block-title">
            <strong><span><?php echo $this->__('Shop By') ?></span></strong>
        </div>
        <?php echo $this->getStateHtml() ?>
        <div class="block-content">
            <?php if($this->canShowOptions()): ?>
                <h3><?php echo $this->__('Shopping Options') ?></h3>
                <dl>
                    <?php $_filters = $this->getFilters() ?>
                    <?php foreach ($_filters as $_filter): ?>
                        <?php if($_filter->getItemsCount()): ?>
                            <dt><?php echo $this->__($_filter->getName()) ?></dt>
                            <dd><?php echo $_filter->getHtml() ?></dd>
                        <?php endif; ?>
                    <?php endforeach; ?>
                </dl>
            <?php endif; ?>
            <?php if ($this->getLayer()->getState()->getFilters()): ?>
                <div class="actions">
                    <a href="<?php echo $this->getClearUrl() ?>"><?php echo $this->__('Clear All') ?></a>
                </div>
            <?php endif; ?>
        </div>
    </div>
<?php endif; ?>
