<?php $_items = $this->getReviewsCollection()->getItems();?>
<div class="box-collateral box-reviews" id="customer-reviews">
    <?php if (count($_items)) : ?>
        <div class="block-title">
            <h2><?php echo $this->__('Customer Reviews') ?></h2>
        </div>
        <?php echo $this->getChildHtml('toolbar') ?>
            <?php foreach ($_items as $_review):?>
                <article itemprop="review" itemscope itemtype="http://schema.org/Review">
                    <h3 itemprop="name"><?php echo $this->htmlEscape($_review->getTitle()) ?></h3>
                    <em itemprop="author"><?php echo $this->htmlEscape($_review->getNickname()); ?></em>,
                    <time itemprop="datePublished"><?php echo $this->formatDate($_review->getCreatedAt()); ?></time>
                    <?php $_votes = $_review->getRatingVotes(); ?>
                    <?php if (count($_votes)): ?>
                        <span itemprop="reviewRating" itemscope itemtype="http://schema.org/Rating">
                            <?php foreach ($_votes as $_vote): ?>
                                <span class="vote" itemprop="ratingValue"><?php echo $_vote->getPercent()/20; ?></span> <?php echo $this->__('of'); ?>
                                <span class="vote" itemprop="bestRating">5</span>
                            <?php endforeach; ?>
                        </span>
                    <?php endif; ?>
                    <p itemprop="description"><?php echo nl2br($this->htmlEscape($_review->getDetail())) ?></p>
                </article>
            <?php endforeach; ?>
        </dl>
        <?php echo $this->getChildHtml('toolbar') ?>
    <?php endif;?>
    <?php echo $this->getChildHtml('review_form') ?>
</div>