<?php
/**
 * @see Enterprise_GiftCardAccount_Block_Checkout_Cart_Giftcardaccount
 *
 */
?>
<div class="giftcard">
    <h2><?php echo $this->__('Gift Cards') ?></h2>
    <div id="giftcard_balance_lookup"></div>
    <span id="gc-please-wait" class="please-wait" style="display:none;">
        <img src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif') ?>" alt="" class="v-middle" />
        <?php echo $this->__('Please wait, loading...') ?>
    </span>
    <form id="giftcard-form" action="<?php echo $this->getUrl('enterprise_giftcardaccount/cart/add') ?>" method="post">
        <label for="giftcard_code"><?php echo $this->__('Enter the gift card code') ?></label>
        <input class="required-entry input-text" id="giftcard_code" name="giftcard_code" />
        <button class="button"
            id="addGiftCard"
            type="button"
            value="<?php echo $this->__('Add Gift Card') ?>"><span><?php echo $this->__('Add Gift Card') ?></span></button>
        <button class="button check-gc-status"
            id="checkGiftCardStatus"
            type="button"
            value="<?php echo $this->__('Check Gift Card status and balance') ?>"><span><?php echo $this->__('Check Gift Card status and balance') ?></span></button>
    </form>

    <script>
        document.observe('dom:loaded', function() {
            var giftcardForm = new VarienForm('giftcard-form');
            function checkGiftCardStatus() {
                if (giftcardForm.validator && !giftcardForm.validator.validate()) {
                    return false;
                }
                new Ajax.Updater(
                    'giftcard_balance_lookup',
                    '<?php echo Mage::getUrl('enterprise_giftcardaccount/cart/quickCheck') ?>',
                    {
                        onCreate: function() { $('gc-please-wait').show(); },
                        onComplete: function() { $('gc-please-wait').hide(); },
                        parameters : {giftcard_code : $('giftcard_code').value}
                    }
                );
            }

            if($('addGiftCard')) {
                $('addGiftCard').observe('click', function(event) {
                    giftcardForm.submit();
                });
            }
            if($('checkGiftCardStatus')) {
                $('checkGiftCardStatus').observe('click', function(event) {
                    checkGiftCardStatus();
                });
            }
        });
    </script>
</div>
