<?php
/**
 * @var $this Mage_Wishlist_Block_Customer_Wishlist_Item_Column_Cart
 * @var Mage_Wishlist_Model_Item $item
 *
 */

$item = $this->getItem();
$product = $item->getProduct();
?>
<?php echo $this->getPriceHtml($product);?>
<div class="add-to-cart-alt">
    <?php if($item->canHaveQty() && $item->getProduct()->isVisibleInSiteVisibility()) : ?>
        <input type="hidden" name="qty[<?php echo $item->getId() ?>]" value="<?php echo $this->getAddToCartQty($item) * 1 ?>" />
    <?php endif; ?>
    <?php if ($product->isSaleable()): ?>
        <button type="button" title="<?php echo $this->__('Add to Cart') ?>" onclick="addWItemToCart(<?php echo $item->getId()?>);" class="button primary"><span><?php echo $this->__('Buy') ?></span></button>
    <?php else : ?>
        <?php if ($product->getIsSalable()): ?>
            <p class="availability in-stock"><span><?php echo $this->__('In stock') ?></span></p>
        <?php else : ?>
            <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
        <?php endif; ?>
    <?php endif; ?>
</div>

<?php foreach($this->getSortedChildren() as $childName) : ?>
    <?php echo $this->getChildHtml($childName, false); ?>
<?php endforeach; ?>
<a href="<?php echo $this->getItemRemoveUrl($this->getItem()); ?>"
    title="<?php echo $this->__('Remove Item') ?>"
    class="btn-remove btn-remove2"><?php echo $this->__('Remove item');?></a>

<textarea name="description[<?php echo $item->getWishlistItemId() ?>]"
    rows="3"
    cols="5"
    placeholder="<?php echo $this->__('Comment') ?>"
    title="<?php echo $this->__('Comment') ?>"><?php echo ($this->escapeHtml($item->getDescription())) ?></textarea>