<?php
/**
 * Product list template (forced grid)
 *
 * @see Mage_Catalog_Block_Product_List
 */

$_productCollection=$this->getLoadedProductCollection();
$_helper = $this->helper('catalog/output');
?>

<?php if(!$_productCollection->count()) : ?>
    <p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
<?php else: ?>
    <div class="category-products">
        <ul class="products-grid">
            <?php foreach($_productCollection as $_product) : ?>
                <li class="item">
                    <a href="<?php echo $_product->getProductUrl() ?>"
                        title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>"
                        class="product-image">
                        <img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(256); ?>"
                            alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />
                    </a>
                    <h2 class="product-name">
                        <a href="<?php echo $_product->getProductUrl() ?>"
                            title="<?php echo $this->stripTags($_product->getName(), null, true) ?>">
                            <?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></a>
                    </h2>
                    <?php echo $this->getPriceHtml($_product, true) ?>
                </li>
            <?php endforeach ?>
        </ul>
    </div>

    <?php echo $this->getToolbarHtml() ?>
<?php endif; ?>