<?php
/**
 * Product list template (forced grid)
 *
 * @see Mage_Catalog_Block_Product_List
 */

$_productCollection=$this->getLoadedProductCollection();
$_helper = $this->helper('catalog/output');
?>

<?php if(!$_productCollection->count()) : ?>
    <p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
<?php else: ?>
    <div class="category-products">
        <?php
        /**
         * The `productList` block needs to be added in the layout as a child and
         * be of the same type as this one.
         */
        $this->getChild('productList')->setData(array(
            'products' => $_productCollection,
            'toolbar'  => true));
        echo $this->getChildHtml('productList');
        ?>
    </div>
<?php endif; ?>