
<?php
/**
 * Category view template
 *
 * @see Mage_Catalog_Block_Category_View
 */

$_helper    = $this->helper('catalog/output');
$_category  = $this->getCurrentCategory();
$_imgHtml   = '';
if($_imgUrl = $_category->getImageUrl()) {
    $_imgHtml = '<p class="category-image"><img src="'.$_imgUrl.'" alt="'.$this->htmlEscape($_category->getName()).'" title="'.$this->htmlEscape($_category->getName()).'" /></p>';
    $_imgHtml = $_helper->categoryAttribute($_category, $_imgHtml, 'image');
}
?>
<?php echo $this->getMessagesBlock()->toHtml() ?>
<div class="category-view">
    <?php if($_imgUrl) : ?>
        <?php echo $_imgHtml ?>
    <?php endif; ?>

    <?php if($_description=$this->getCurrentCategory()->getDescription()) : ?>
        <p class="category-description">
            <?php echo $_helper->categoryAttribute($_category, $_description, 'description') ?>
        </p>
    <?php endif; ?>

    <?php if($this->isContentMode()) : ?>
        <?php echo $this->getCmsBlockHtml() ?>
    <?php elseif($this->isMixedMode()) : ?>
        <?php echo $this->getCmsBlockHtml() ?>
        <?php echo $this->getProductListHtml() ?>
    <?php else : ?>
        <?php echo $this->getProductListHtml() ?>
    <?php endif; ?>
</div>
