<article>
<div id="messages_product_view"><?php echo $this->getMessagesBlock()->getGroupedHtml() ?></div>
    <header>
        <h1><?php echo $this->__('Contact Us') ?></h1>
    </header>
    <form action="<?php echo $this->getFormAction(); ?>" id="contactForm" method="post">
        <p>
            <label for="comment" class="required"><?php echo $this->__('Message') ?></label>
            <textarea name="comment"
                id="comment"
                title="<?php echo $this->__('Comment') ?>"
                class="required-entry"
                cols="10"
                rows="7"></textarea>
        </p>
        <p>
            <label for="name" class="required"><?php echo $this->__('Name') ?></label>
            <input name="name"
                type="text"
                id="name"
                title="<?php echo $this->__('Name') ?>"
                value="<?php echo $this->htmlEscape($this->helper('contacts')->getUserName()) ?>"
                class="required-entry" />
        </p>
        <p>
            <label for="email" class="required"><?php echo $this->__('Email') ?></label>
            <input name="email"
                type="email"
                id="email" title="<?php echo $this->__('Email') ?>"
                value="<?php echo $this->htmlEscape($this->helper('contacts')->getUserEmail()) ?>"
                class="required-entry validate-email" />
        </p>
        <p>
            <label for="telephone"><?php echo $this->__('Telephone') ?> <span class="optional">(<?php echo $this->__('optional'); ?>)</span></label>
            <input name="telephone"
                id="telephone"
                type="tel"
                title="<?php echo Mage::helper('contacts')->__('Telephone') ?>" />
        </p>

        <input type="text" name="hideit" id="hideit" value="" style="display:none !important;" />

        <button type="submit" class="button"><span><?php echo $this->__('Send Message') ?></span></button>
    </form>
</article>
<script>
    document.observe('dom:loaded', function() {
        var contactForm = new VarienForm('contactForm', true);
    });
</script>