<?php
/**
 * @var $this Mage_Tax_Block_Checkout_Grandtotal
 * @see Mage_Tax_Block_Checkout_Grandtotal
 */
?>
<?php if ($this->includeTax() && $this->getTotalExclTax()>=0):?>
    <tr class="totals__grand-total totals__grand-total--excl">
        <td style="<?php echo $this->getStyle() ?>" colspan="<?php echo $this->getColspan(); ?>">
            <strong><?php echo $this->helper('tax')->__('Grand Total Excl. Tax')?></strong>
        </td>
        <td style="<?php echo $this->getStyle() ?>" class="right">
            <strong><?php echo $this->helper('checkout')->formatPrice($this->getTotalExclTax()) ?></strong>
        </td>
    </tr>
    <?php echo $this->renderTotals('taxes', $this->getColspan()); ?>
    <tr class="totals__grand-total totals__grand-total--incl">
        <td style="<?php echo $this->getStyle() ?>" colspan="<?php echo $this->getColspan(); ?>">
            <strong><?php echo $this->helper('tax')->__('Grand Total Incl. Tax')?></strong>
        </td>
        <td style="<?php echo $this->getStyle() ?>" class="right">
            <strong><?php echo $this->helper('checkout')->formatPrice($this->getTotal()->getValue()) ?></strong>
        </td>
    </tr>
<?php else : ?>
    <tr class="totals__grand-total">
        <td style="<?php echo $this->getStyle() ?>" colspan="<?php echo $this->getColspan(); ?>">
            <strong><?php echo $this->getTotal()->getTitle() ?></strong>
        </td>
        <td style="<?php echo $this->getStyle() ?>" class="right">
            <strong><?php echo $this->helper('checkout')->formatPrice($this->getTotal()->getValue()) ?></strong>
        </td>
    </tr>
<?php endif;?>
