<?php
/**
 * @var $this Mage_Tax_Block_Checkout_Shipping
 * @see Mage_Tax_Block_Checkout_Shipping
 */
?>
<?php if($this->displayBoth()) : ?>
    <tr class="totals__shipping totals__shipping--excl">
        <td style="<?php echo $this->getStyle() ?>" colspan="<?php echo $this->getColspan(); ?>">
            <?php echo $this->getExcludeTaxLabel() ?>
        </td>
        <td style="<?php echo $this->getStyle() ?>" class="right">
            <?php echo $this->helper('checkout')->formatPrice($this->getShippingExcludeTax()) ?>
        </td>
    </tr>
    <tr class="totals__shipping totals__shipping--incl">
        <td style="<?php echo $this->getStyle() ?>" colspan="<?php echo $this->getColspan(); ?>">
            <?php echo $this->getIncludeTaxLabel() ?>
        </td>
        <td style="<?php echo $this->getStyle() ?>" class="right">
            <?php echo $this->helper('checkout')->formatPrice($this->getShippingIncludeTax()) ?>
        </td>
    </tr>
<?php elseif($this->displayIncludeTax()) : ?>
    <tr class="totals__shipping totals__shipping--incl">
        <td style="<?php echo $this->getStyle() ?>" colspan="<?php echo $this->getColspan(); ?>">
            <?php echo $this->getTotal()->getTitle() ?>
        </td>
        <td style="<?php echo $this->getStyle() ?>" class="right">
            <?php echo $this->helper('checkout')->formatPrice($this->getShippingIncludeTax()) ?>
        </td>
    </tr>
<?php else : ?>
    <tr class="totals__shipping totals__shipping--excl">
        <td style="<?php echo $this->getStyle() ?>" colspan="<?php echo $this->getColspan(); ?>">
            <?php echo $this->escapeHtml($this->getTotal()->getTitle()) ?>
        </td>
        <td style="<?php echo $this->getStyle() ?>" class="right">
            <?php echo $this->helper('checkout')->formatPrice($this->getShippingExcludeTax()) ?>
        </td>
    </tr>
<?php endif; ?>
