<?php
/**
 * @var $this Mage_Tax_Block_Checkout_Subtotal
 * @see Mage_Tax_Block_Checkout_Subtotal
 */
?>
<?php if ($this->displayBoth()):?>
    <tr class="totals__subtotal totals__subtotal--excl">
        <td style="<?php echo $this->getStyle() ?>" colspan="<?php echo $this->getColspan(); ?>">
            <?php echo $this->helper('tax')->__('Subtotal (Excl. Tax)') ?>
        </td>
        <td style="<?php echo $this->getStyle() ?>" class="right">
            <?php echo $this->helper('checkout')->formatPrice($this->getTotal()->getValueExclTax()) ?>
        </td>
    </tr>
    <tr class="totals__subtotal totals__subtotal--incl">
        <td style="<?php echo $this->getStyle() ?>" colspan="<?php echo $this->getColspan(); ?>">
            <?php echo $this->helper('tax')->__('Subtotal (Incl. Tax)') ?>
        </td>
        <td style="<?php echo $this->getStyle() ?>" class="right">
            <?php echo $this->helper('checkout')->formatPrice($this->getTotal()->getValueInclTax()) ?>
        </td>
    </tr>
<?php else : ?>
    <tr class="totals__subtotal">
        <td style="<?php echo $this->getStyle() ?>" colspan="<?php echo $this->getColspan(); ?>">
            <?php echo $this->getTotal()->getTitle() ?>
        </td>
        <td style="<?php echo $this->getStyle() ?>" class="right">
            <?php echo $this->helper('checkout')->formatPrice($this->getTotal()->getValue()) ?>
        </td>
    </tr>
<?php endif;?>
