<form id="search_mini_form"
    class="form-search"
    action="<?php echo $this->helper('catalogsearch')->getResultUrl() ?>">
    <input id="search"
        type="search"
        name="<?php echo $this->helper('catalogsearch')->getQueryParamName() ?>"
        value="<?php echo $this->helper('catalogsearch')->getEscapedQueryText() ?>"
        placeholder="<?php echo $this->__('Search') ?>" />
    <input type="hidden" name="order" value="relevance" />
    <input type="hidden" name="dir" value="desc" />
    <input type="submit" title="<?php echo $this->__('Search') ?>" />
    <div id="search_autocomplete" class="search-autocomplete"></div>
    <script>
        document.observe('dom:loaded', function() {
            var searchForm = new Varien.searchForm('search_mini_form', 'search', '<?php echo $this->__('Search entire store here...') ?>');
            searchForm.initAutocomplete('<?php echo $this->helper('catalogsearch')->getSuggestUrl() ?>', 'search_autocomplete');
        });
    </script>
</form>