<?php
/**
 * @see Mage_Page_Block_Template_Links
 *
 */
?>
<?php if(count($_links = $this->getLinks())>0): ?>
    <ul class="links"<?php if($this->getName()): ?> id="<?php echo $this->getName() ?>"<?php endif;?>>
        <li class="info"><?php echo $this->__('Customer Support phone.'); ?> <span class="phone"><?php echo Mage::getStoreConfig('general/store_information/phone'); ?></span></li>
        <?php foreach($_links as $_link): ?>
            <?php if ($_link instanceof Mage_Core_Block_Abstract):?>
                <?php echo $_link->toHtml(); ?>
            <?php else : if($_link->getLabel()) : ?>
                <li<?php if($_link->getIsFirst()||$_link->getIsLast()): ?>
                    class="<?php if($_link->getIsFirst()): ?>first<?php endif; ?><?php if($_link->getIsLast()): ?> last<?php endif; ?>"<?php endif; ?>
                    <?php echo $_link->getLiParams() ?>>
                    <?php echo $_link->getBeforeText() ?>
                    <a href="<?php echo $_link->getUrl() ?>"
                        title="<?php echo $_link->getTitle() ?>"
                        <?php echo $_link->getAParams() ?>>
                            <?php echo $_link->getLabel(); ?>
                    </a>
                    <?php echo $_link->getAfterText() ?>
                </li>
            <?php endif; endif; ?>
        <?php endforeach; ?>
    </ul>
<?php endif; ?>
