<?php
/**
 * Billing address form
 *
 */

$_helper      = $this->helper('customer/address');
$_streetLines = $_helper->getStreetLines();
$_fieldsToValidate = array(
    'company',
    'street',
    'vat_id',
    'city',
    'region',
    'postcode',
    'telephone');

foreach ($_fieldsToValidate as $key) {
    $_validationClass[$key] = $_helper->getAttributeValidationClass($key);
}

$_validationClass['streetAlt'] = trim(str_replace('required-entry', '', $_validationClass['street']));
?>
<form action="" id="co-billing-form" class="address-form<?php echo $this->isPrimaryAddress() ? ' primary' : ''; ?>">
    <h2><?php echo $this->__('Billing Address'); ?></h2>

    <ul class="form-list">
        <?php if ($this->isPrimaryAddress()): ?>
            <?php echo $this->getChildHtml('get_address'); ?>
        <?php endif; ?>
        <?php
            /**
             * If customer has adresses
             *
             * If customer is logged in and has saved adresses, we should show
             * a select element with the customer's addresses
             */
            if ($this->customerHasAddresses()):
        ?>
        <li class="from-address-book">
            <label for="billing-address-select"><?php echo $this->__('Select a billing address from your address book or enter a new address.') ?></label>
            <?php echo $this->getAddressesHtmlSelect('billing') ?>
        </li>
        <?php endif ?>

        <li id="billing-new-address-form"<?php if ($this->customerHasAddresses()): ?> style="display:none;"<?php endif; ?>>
            <fieldset>

                <input type="hidden" name="billing[address_id]" value="<?php echo $this->getAddress()->getId() ?>" id="billing:address_id" />

                <ul>
                    <li>
                        <?php
                        /**
                         * First name and last name
                         */
                        echo $this->getLayout()->createBlock('customer/widget_name')
                            ->setObject($this->getAddress())
                            ->setFieldIdFormat('billing:%s')
                            ->setFieldNameFormat('billing[%s]')
                            ->toHtml();
                        ?>
                    </li>
                    <li class="contacts">
                    <?php
                    /**
                     * If billing address is the primary address
                     * and the user is not logged in, show field
                     * for email address here
                     */
                    if(!$this->isCustomerLoggedIn() && $this->isPrimaryAddress()): ?>
                        <div class="field">
                            <label for="billing:email" class="required"><?php echo $this->__('Email Address') ?> <em>*</em></label>
                            <input
                                type="text"
                                name="billing[email]"
                                id="billing:email"
                                value="<?php echo $this->escapeHtml($this->getAddress()->getEmail()) ?>"
                                title="<?php echo $this->__('Email Address') ?>"
                                class="input-text validate-email required-entry" />
                        </div>
                    <?php endif; ?>
                        <div class="field">
                            <label for="billing:telephone" class="required">
                                <?php echo $this->__('Telephone') ?> <em>*</em>
                            </label>
                            <input
                                type="text"
                                name="billing[telephone]"
                                value="<?php echo $this->escapeHtml($this->getAddress()->getTelephone()) ?>"
                                title="<?php echo $this->__('Telephone') ?>"
                                class="input-text <?php echo $_validationClass['telephone'] ?>"
                                id="billing:telephone" />
                        </div>
                    </li>
                    <li>
                        <label for="billing:company"><?php echo $this->__('Company') ?></label>
                        <input
                            type="text"
                            id="billing:company"
                            name="billing[company]"
                            value="<?php echo $this->escapeHtml($this->getAddress()->getCompany()) ?>"
                            title="<?php echo $this->__('Company') ?>"
                            class="input-text <?php echo $_validationClass['company'] ?>" />
                    </li>
                    <li class="street">
                        <label for="billing:street1" class="required"><?php echo $this->__('Address') ?> <em>*</em></label>
                        <div class="field">
                            <input
                                type="text"
                                title="<?php echo $this->__('Street Address') ?>"
                                name="billing[street][]"
                                id="billing:street1"
                                value="<?php echo $this->escapeHtml($this->getAddress()->getStreet(1)) ?>"
                                class="input-text <?php echo $_validationClass['street'] ?>" />
                        </div>
                        <?php for ($_i = 2, $_n = $_streetLines; $_i <= $_n; $_i++): ?>
                        <div class="field">
                            <input
                                type="text"
                                title="<?php echo $this->__('Street Address %s', $_i) ?>"
                                name="billing[street][]"
                                id="billing:street<?php echo $_i ?>"
                                value="<?php echo $this->escapeHtml($this->getAddress()->getStreet($_i)) ?>"
                                class="input-text <?php echo $_validationClass['streetAlt'] ?>" />
                        </div>
                        <?php endfor; ?>
                    </li>

                    <?php
                    /**
                     * If VAT attribute is visible
                     */
                    if ($_helper->isVatAttributeVisible()): ?>
                        <li>
                            <label for="billing:vat_id"><?php echo $this->__('VAT Number'); ?></label>
                            <input
                                type="text"
                                id="billing:vat_id"
                                name="billing[vat_id]"
                                value="<?php echo $this->escapeHtml($this->getAddress()->getVatId()); ?>"
                                title="<?php echo $this->__('VAT Number'); ?>"
                                class="input-text <?php echo $_validationClass['vat'] ?>" />
                        </li>
                    <?php endif; ?>

                        <li class="postaddress">
                            <div class="field">
                                <label for="billing:postcode" class="required">
                                    <?php echo $this->__('Zip/Postal Code') ?> <em>*</em>
                                </label>
                                <input
                                    type="text"
                                    title="<?php echo $this->__('Zip/Postal Code') ?>"
                                    name="billing[postcode]"
                                    id="billing:postcode"
                                    value="<?php echo $this->escapeHtml($this->getAddress()->getPostcode()) ?>"
                                    class="input-text validate-zip-international <?php echo $_validationClass['postcode'] ?>" />
                            </div>
                            <div class="field">
                                <label for="billing:city" class="required"><?php echo $this->__('City') ?> <em>*</em></label>
                                <input
                                    type="text"
                                    title="<?php echo $this->__('City') ?>"
                                    name="billing[city]"
                                    value="<?php echo $this->escapeHtml($this->getAddress()->getCity()) ?>"
                                    class="input-text <?php echo $_validationClass['city'] ?>"
                                    id="billing:city" />
                            </div>
                        </li>
                        <li class="billing-region">
                            <label for="billing:region" class="required">
                                <?php echo $this->__('State/Province') ?> <em>*</em>
                            </label>
                            <select id="billing:region_id"
                                name="billing[region_id]"
                                title="<?php echo $this->__('State/Province') ?>"
                                class="validate-select"
                                style="display:none;">
                                <option value=""><?php echo $this->__('Please select region, state or province') ?></option>
                            </select>
                            <input
                                type="text"
                                id="billing:region"
                                name="billing[region]"
                                value="<?php echo $this->escapeHtml($this->getAddress()->getRegion()) ?>"
                                title="<?php echo $this->__('State/Province') ?>"
                                class="input-text <?php echo $_validationClass['region'] ?>"
                                style="display:none;" />
                        </li>
                        <li>
                            <label for="billing:country_id" class="required">
                                <?php echo $this->__('Country') ?> <em>*</em>
                            </label>
                            <?php echo $this->getCountryHtmlSelect('billing') ?>
                        </li>
                        <?php // Customer not logged in
                        if(!$this->isCustomerLoggedIn()):
                            $_dob = $this->getLayout()->createBlock('customer/widget_dob');
                            $_gender = $this->getLayout()->createBlock('customer/widget_gender');
                            ?>

                            <?php if ($_dob->isEnabled()): ?>
                                <li>
                                    <?php echo $_dob->setDate($this->getQuote()->getCustomerDob())->setFieldIdFormat('billing:%s')->setFieldNameFormat('billing[%s]')->toHtml() ?>
                                </li>
                            <?php endif; ?>

                            <?php if ($_gender->isEnabled()): ?>
                                <li>
                                    <?php echo $_gender->setGender($this->getQuote()->getCustomerGender())->setFieldIdFormat('billing:%s')->setFieldNameFormat('billing[%s]')->toHtml() ?>
                                </li>
                            <?php endif; ?>

                            <?php
                            $_taxvat = $this->getLayout()->createBlock('customer/widget_taxvat');
                            if ($_taxvat->isEnabled()): ?>
                                <li>
                                    <?php echo $_taxvat->setTaxvat($this->getQuote()->getCustomerTaxvat())->setFieldIdFormat('billing:%s')->setFieldNameFormat('billing[%s]')->toHtml() ?>
                                </li>
                            <?php endif ?>

                            <?php if ($this->isPrimaryAddress()) : ?>
                                <li class="fields" id="register-customer-password">
                                    <div class="field">
                                        <label for="billing:customer_password" class="required"><?php echo $this->__('Password') ?> <em>*</em></label>
                                        <div class="input-box">
                                            <input type="password" name="billing[customer_password]" id="billing:customer_password" title="<?php echo $this->__('Password') ?>" class="input-text required-entry validate-password" />
                                        </div>
                                    </div>
                                    <div class="field">
                                        <label for="billing:confirm_password" class="required"><?php echo $this->__('Confirm Password') ?> <em>*</em></label>
                                        <div class="input-box">
                                            <input type="password" name="billing[confirm_password]" title="<?php echo $this->__('Confirm Password') ?>" id="billing:confirm_password" class="input-text required-entry validate-cpassword" />
                                        </div>
                                    </div>
                                </li>
                            <?php endif; ?>
                        <?php endif; // !$this->isCustomerLoggedIn() ?>

                        <?php if ($this->isCustomerLoggedIn() && $this->customerHasAddresses()) : ?>
                        <li>
                            <label for="billing:save_in_address_book">
                            <input
                                type="checkbox"
                                name="billing[save_in_address_book]"
                                value="1"
                                title="<?php echo $this->__('Save in address book') ?>"
                                id="billing:save_in_address_book"
                                <?php if ($this->getAddress()->getSaveInAddressBook()): ?>
                                checked="checked"
                                <?php endif;?>
                                class="checkbox" />
                                <?php echo $this->__('Save in address book') ?>
                            </label>
                        </li>
                    </ul>
                <?php else : // $_helper->isVatAttributeVisible() ?>
                    </ul>

                    <input type="hidden" name="billing[save_in_address_book]" value="1" />
                <?php endif; ?>

                <?php if($this->isPrimaryAddress()) : ?>
                    <?php echo $this->getChildHtml('checkout.onepage.billing.newsletter'); ?>
                <?php endif; ?>

                <?php echo $this->getChildHtml('form.additional.info'); ?>
            </fieldset>
        </li>
        <?php
        /**
         * Extensions placeholder
         *
         * Since quite a lot of the checkout is rewritten from
         * the following stuff for extensions might cause problem.
         */
        echo $this->getChildHtml('checkout.onepage.billing.extra');
        ?>

        <?php if ($this->canShip() && $this->isPrimaryAddress()): ?>
            <li><label for="billing:use_for_shipping"><input type="checkbox" id="billing:use_for_shipping" name="billing[use_for_shipping]"<?php if ($this->isUseBillingAddressForShipping()): ?> checked="checked"<?php endif;?> value="1" /> <?php echo $this->__('Use this address for shipping'); ?></label></li>
        <?php endif; ?>
    </ul>

    <?php
    /**
     * Quote contains virtual products, so shipping address
     * won't be visible for customer – force it billing address
     * to shipping address.
     **/
    if (!$this->canShip()):
    ?>
    <input type="hidden" name="billing[use_for_shipping]" value="1" />
    <?php endif; ?>
</form>

<script>
    new Validation('co-billing-form');
    var billingForm,
        billingRegionUpdater,
        billingAddress;

    document.observe('dom:loaded', function() {
        billingForm          = new VarienForm('co-billing-form');
        billingRegionUpdater = new RegionUpdater(
                                        'billing:country_id',
                                        'billing:region',
                                        'billing:region_id',
                                        <?php echo $this->helper('directory')->getRegionJson() ?>,
                                        undefined,
                                        'billing:postcode'
                                    );
        billingAddress           = new BillingAddress({
            form:    'co-billing-form',
            test1:   '<?php echo $this->getUrl('checkout/onepage/getAddress') ?>address/',
            saveUrl: '<?php echo $this->getUrl('checkout/onepage/saveBilling') ?>',
            relations: ['payment','review'],
            customerEmailExistsUrl: '<?php echo $this->getUrl('checkout/onepage/customerEmailExists') ?>'
        });

        $('billing-address-select') && billingAddress.newAddress(!$('billing-address-select').value);
    });
</script>
