<?php
/**
 * Shipping address form
 *
 */

$_helper      = $this->helper('customer/address');
$_streetLines = $_helper->getStreetLines();
$_fieldsToValidate = array(
    'company',
    'street',
    'vat_id',
    'city',
    'region',
    'postcode',
    'telephone');

foreach ($_fieldsToValidate as $key) {
    $_validationClass[$key] = $_helper->getAttributeValidationClass($key);
}

$_validationClass['streetAlt'] = trim(str_replace('required-entry', '', $_validationClass['street']));
?>
<form action="" id="co-shipping-form" class="address-form<?php echo $this->isPrimaryAddress() ? ' primary' : ''; ?>">
    <h2><?php echo $this->__('Shipping Address'); ?></h2>

    <ul class="form-list">
        <?php if ($this->isPrimaryAddress()): ?>
            <?php echo $this->getChildHtml('get_address'); ?>
        <?php endif; ?>
        <?php
        /**
         * If customer has adresses
         *
         * If customer is logged in and has saved adresses, we should show
         * a select element with the customer's addresses
         */
        if ($this->customerHasAddresses()): ?>
            <li class="from-address-book">
                <label for="shipping-address-select"><?php echo $this->__('Select a shipping address from your address book or enter a new address.') ?></label>
                <?php echo $this->getAddressesHtmlSelect('shipping') ?>
            </li>
        <?php endif ?>

        <li id="shipping-new-address-form"<?php if ($this->customerHasAddresses()): ?> style="display:none;"<?php endif; ?>>
            <input type="hidden" name="shipping[address_id]" value="<?php echo $this->getAddress()->getId() ?>" id="shipping:address_id" />

            <ul>
                <li>
                    <?php
                    /**
                     * First name and last name
                     */
                    echo $this->getLayout()->createBlock('customer/widget_name')
                        ->setObject($this->getAddress())
                        ->setFieldIdFormat('shipping:%s')
                        ->setFieldNameFormat('shipping[%s]')
                        ->toHtml();
                    ?>
                </li>
                <li class="contacts">
                <?php
                /**
                 * If billing address is the primary address
                 * and the user is not logged in, show field
                 * for email address here
                 */
                if(!$this->isCustomerLoggedIn() && $this->isPrimaryAddress()):
                ?>
                    <div class="field input-box">
                        <label for="shipping:email" class="required"><?php echo $this->__('Email Address') ?></label>
                        <input
                            type="text"
                            name="shipping[email]"
                            id="shipping:email"
                            value="<?php echo $this->escapeHtml($this->getAddress()->getEmail()) ?>"
                            title="<?php echo $this->__('Email Address') ?>"
                            class="input-text validate-email required-entry" />
                    </div>
                <?php endif; ?>
                    <div class="field">
                        <label for="shipping:telephone" class="required">
                            <?php echo $this->__('Telephone') ?>
                        </label>
                        <input
                            type="text"
                            name="shipping[telephone]"
                            value="<?php echo $this->escapeHtml($this->getAddress()->getTelephone()) ?>"
                            title="<?php echo $this->__('Telephone') ?>"
                            class="input-text <?php echo $_validationClass['telephone'] ?>"
                            id="shipping:telephone" />
                    </div>
                </li>
                <li>
                    <label for="shipping:company"><?php echo $this->__('Company') ?> <span>(<?php echo $this->__('optional'); ?>)</span></label>
                    <input
                        type="text"
                        id="shipping:company"
                        name="shipping[company]"
                        value="<?php echo $this->escapeHtml($this->getAddress()->getCompany()) ?>"
                        title="<?php echo $this->__('Company') ?>"
                        class="input-text <?php echo $_validationClass['company'] ?>" />
                </li>
                <li class="street">
                    <label for="shipping:street1" class="required"><?php echo $this->__('Address') ?></label>
                    <div class="field">
                        <input
                            type="text"
                            title="<?php echo $this->__('Street Address') ?>"
                            name="shipping[street][]"
                            id="shipping:street1"
                            value="<?php echo $this->escapeHtml($this->getAddress()->getStreet(1)) ?>"
                            class="input-text <?php echo $_validationClass['street'] ?>" />
                    </div>
                    <?php for ($_i = 2, $_n = $_streetLines; $_i <= $_n; $_i++): ?>
                        <div class="field">
                            <input
                                type="text"
                                title="<?php echo $this->__('Street Address %s', $_i) ?>"
                                name="shipping[street][]"
                                id="shipping:street<?php echo $_i ?>"
                                value="<?php echo $this->escapeHtml($this->getAddress()->getStreet($_i)) ?>"
                                class="input-text <?php echo $_validationClass['streetAlt'] ?>" />
                        </div>
                    <?php endfor; ?>
                </li>
                <?php
                /**
                 * If VAT attribute is visible
                 */
                if ($_helper->isVatAttributeVisible()):
                ?>
                    <li>
                        <label for="billing:vat_id"><?php echo $this->__('VAT Number'); ?></label>
                        <input
                            type="text"
                            id="shipping:vat_id"
                            name="shipping[vat_id]"
                            value="<?php echo $this->escapeHtml($this->getAddress()->getVatId()); ?>"
                            title="<?php echo $this->__('VAT Number'); ?>"
                            class="input-text <?php echo $_validationClass['vat'] ?>" />
                    </li>
                <?php endif; ?>
                <li class="postaddress">
                    <div class="field">
                    <label for="shipping:postcode" class="required">
                        <?php echo $this->__('Zip/Postal Code') ?>
                    </label>
                    <input
                        type="text"
                        title="<?php echo $this->__('Zip/Postal Code') ?>"
                        name="shipping[postcode]"
                        id="shipping:postcode"
                        value="<?php echo $this->escapeHtml($this->getAddress()->getPostcode()) ?>"
                        class="input-text validate-zip-international <?php echo $_validationClass['postcode'] ?>" />
                    </div>
                    <div class="field">
                    <label for="shipping:city" class="required"><?php echo $this->__('City') ?></label>
                    <input
                        type="text"
                        title="<?php echo $this->__('City') ?>"
                        name="shipping[city]"
                        value="<?php echo $this->escapeHtml($this->getAddress()->getCity()) ?>"
                        class="input-text <?php echo $_validationClass['city'] ?>"
                        id="shipping:city" />
                    </div>
                </li>
                <li class="shipping-region">
                    <label for="shipping:region" class="required">
                        <?php echo $this->__('State/Province') ?>
                    </label>
                    <select id="shipping:region_id"
                        name="shipping[region_id]"
                        title="<?php echo $this->__('State/Province') ?>"
                        class="validate-select"
                        style="display:none;">
                        <option value=""><?php echo $this->__('Please select region, state or province') ?></option>
                    </select>
                    <input
                        type="text"
                        id="shipping:region"
                        name="shipping[region]"
                        value="<?php echo $this->escapeHtml($this->getAddress()->getRegion()) ?>"
                        title="<?php echo $this->__('State/Province') ?>"
                        class="input-text <?php echo $_validationClass['region'] ?>"
                        style="display:none;" />
                </li>
                <li>
                    <label for="shipping:country_id" class="required">
                        <?php echo $this->__('Country') ?>
                    </label>
                    <?php echo $this->getCountryHtmlSelect('shipping') ?>
                </li>
                <?php if(!$this->isCustomerLoggedIn() && $this->isPrimaryAddress()): ?>
                    <li class="fields" id="register-customer-password">
                        <div class="field">
                            <label for="shipping:customer_password" class="required"><?php echo $this->__('Password') ?></label>
                            <div class="input-box">
                                <input type="password" name="shipping[customer_password]" id="shipping:customer_password" title="<?php echo $this->__('Password') ?>" class="input-text required-entry validate-password" />
                            </div>
                        </div>
                        <div class="field">
                            <label for="shipping:confirm_password" class="required"><?php echo $this->__('Confirm Password') ?></label>
                            <div class="input-box">
                                <input type="password" name="shipping[confirm_password]" title="<?php echo $this->__('Confirm Password') ?>" id="shipping:confirm_password" class="input-text required-entry validate-cpassword" />
                            </div>
                        </div>
                    </li>
                <?php endif; ?>

                <?php if($this->isPrimaryAddress()) : ?>
                    <li><?php echo $this->getChildHtml('checkout.onepage.shipping.newsletter'); ?></li>
                <?php endif; ?>

                <?php if ($this->isCustomerLoggedIn() && $this->customerHasAddresses()): ?>
                    <li>
                        <label for="shipping:save_in_address_book">
                            <input
                                type="checkbox"
                                name="shipping[save_in_address_book]"
                                value="1"
                                title="<?php echo $this->__('Save in address book') ?>"
                                id="shipping:save_in_address_book"
                                <?php if ($this->getAddress()->getSaveInAddressBook()): ?>
                                checked="checked"
                                <?php endif;?>
                                class="checkbox" />
                            <?php echo $this->__('Save in address book') ?>
                        </label>
                    </li>
                    <?php if ($this->isPrimaryAddress()): ?>
                        <li><label for="shipping:use_for_billing"><input type="checkbox" id="shipping:use_for_billing" name="shipping[use_for_billing]" checked="checked" value="1" /> <?php echo $this->__('Use this address for billing'); ?></label></li>
                    <?php endif; ?>
                    </ul>
                <?php else: ?>
                    <?php if ($this->isPrimaryAddress()): ?>
                        <li><label for="shipping:use_for_billing"><input type="checkbox" id="shipping:use_for_billing" name="shipping[use_for_billing]" checked="checked" value="1" /> <?php echo $this->__('Use this address for billing'); ?></label></li>
                    <?php endif; ?>
                </ul>
                <input type="hidden" name="shipping[save_in_address_book]" value="1" />
            <?php endif;?>
        </li>
    </ul>
</form>

<script>
    new Validation('co-shipping-form');

    var shippingForm,
        shippingRegionUpdater,
        shippingForm;

    document.observe('dom:loaded', function() {

        shippingRegionUpdater = new RegionUpdater(
                                        'shipping:country_id',
                                        'shipping:region',
                                        'shipping:region_id',
                                        <?php echo $this->helper('directory')->getRegionJson() ?>,
                                        undefined,
                                        'shipping:postcode'
                                    );
        shippingAddress           = new ShippingAddress({
            form:  'co-shipping-form',
            test:  '<?php echo $this->getUrl('checkout/onepage/getAddress') ?>address/',
            saveUrl: '<?php echo $this->getUrl('checkout/onepage/saveShipping') ?>',
            test3: '<?php echo $this->getUrl('checkout/onepage/shippingMethod') ?>',
            relations: ['payment','shipping_method','review'],
            customerEmailExistsUrl: '<?php echo $this->getUrl('checkout/onepage/customerEmailExists') ?>'
        });
        shippingForm          = new VarienForm('co-shipping-form');
        $('shipping:region_id').setAttribute(
            'defaultValue',
            "<?php echo $this->getAddress()->getRegionId() ?>"
        );
        $('shipping-address-select') && shippingAddress.newAddress(!$('shipping-address-select').value);
    });
</script>
