<article class="account-login">
    <header class="page-title">
        <h1><?php echo $this->__('Login or Create an Account') ?></h1>
    </header>

    <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>

    <div class="new-users">
        <h2><?php echo $this->__('New Customers') ?></h2>
        <p><?php echo $this->__('By creating an account with our store, you will be able to move through the checkout process faster, store multiple shipping addresses, view and track your orders in your account and more.') ?></p>
        <a href="<?php echo $this->getCreateAccountUrl() ?>"
            class="button"
            title="<?php echo $this->__('Create an Account') ?>"><span><?php echo $this->__('Create an Account') ?></span></a>
    </div>

    <div class="registered-users">
        <h2><?php echo $this->__('Registered Customers') ?></h2>
        <p><?php echo $this->__('If you have an account with us, please log in.') ?> <a href="<?php echo $this->getForgotPasswordUrl() ?>" class="f-left"><?php echo $this->__('Forgot Your Password?') ?></a></p>

        <form action="<?php echo $this->getPostActionUrl() ?>" method="post" id="login-form" class="form--layout">
            <ul>
                <li>
                    <label for="email" class="required"><?php echo $this->__('Email Address') ?></label>
                    <input type="email" name="login[username]"
                        value="<?php echo $this->htmlEscape($this->getUsername()) ?>"
                        id="email"
                        class="required-entry validate-email"
                        title="<?php echo $this->__('Email Address') ?>"
                        autofocus />
                </li>
                <li>
                    <label for="pass" class="required"><?php echo $this->__('Password') ?></label>
                    <input type="password" name="login[password]" class="input-text required-entry validate-password" id="pass" title="<?php echo $this->__('Password') ?>" />
                </li>
            </ul>

            <?php echo $this->getChildHtml('persistent.remember.me'); ?>
            <?php echo $this->getChildHtml('persistent.remember.me.tooltip'); ?>
            <p><button type="submit" class="button" title="<?php echo $this->__('Login') ?>" name="send" id="send2"><span><?php echo $this->__('Login') ?></span></button></p>
        </form>
    </div>
</article>

<script>
    document.observe('dom:loaded', function() {
        var dataForm = new VarienForm('login-form', true);
    });
</script>