<article class="account-create">
    <header class="page-title">
        <h1><?php echo $this->__('Create an Account') ?></h1>
    </header>

    <?php echo $this->getChildHtml('form_fields_before')?>

    <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>

    <form action="<?php echo $this->getPostActionUrl() ?>"
        method="post"
        id="form-validate"
        class="form--layout">
        <input type="hidden" name="success_url" value="<?php echo $this->getSuccessUrl() ?>" />
        <input type="hidden" name="error_url" value="<?php echo $this->getErrorUrl() ?>" />


        <ul>
            <li>
                <label for="email_address" class="required"><?php echo $this->__('Email Address') ?></label>
                <input type="email"
                    name="email"
                    id="email_address"
                    value="<?php echo $this->htmlEscape($this->getFormData()->getEmail()) ?>"
                    title="<?php echo $this->__('Email Address') ?>"
                    class="validate-email required-entry"
                    autofocus />
            </li>

            <?php echo $this->getLayout()->createBlock('customer/widget_name')->setObject($this->getFormData())->setForceUseCustomerAttributes(true)->toHtml() ?>

            <?php $_dob = $this->getLayout()->createBlock('customer/widget_dob') ?>
            <?php if ($_dob->isEnabled()): ?>
                <li><?php echo $_dob->setDate($this->getFormData()->getDob())->toHtml() ?></li>
            <?php endif ?>

            <?php $_taxvat = $this->getLayout()->createBlock('customer/widget_taxvat') ?>
            <?php if ($_taxvat->isEnabled()): ?>
                <li><?php echo $_taxvat->setTaxvat($this->getFormData()->getTaxvat())->toHtml() ?></li>
            <?php endif ?>

            <?php $_gender = $this->getLayout()->createBlock('customer/widget_gender') ?>
            <?php if ($_gender->isEnabled()): ?>
                <li><?php echo $_gender->setGender($this->getFormData()->getGender())->toHtml() ?></li>
            <?php endif ?>
        </ul>

        <ul>
            <li>
                <label for="password" class="required"><?php echo $this->__('Password') ?></label>
                <input type="password" name="password" id="password" title="<?php echo $this->__('Password') ?>" class="input-text required-entry validate-password" />
            </li>
            <li>
                <label for="confirmation" class="required"><?php echo $this->__('Confirm Password') ?></label>
                <input type="password" name="confirmation" title="<?php echo $this->__('Confirm Password') ?>" id="confirmation" class="input-text required-entry validate-cpassword" />
            </li>
            <?php if($this->isNewsletterEnabled()) : ?>
                <li class="field--checkbox">
                    <input type="checkbox"
                        name="is_subscribed"
                        title="<?php echo $this->__('Sign Up for Newsletter') ?>"
                        value="1"
                        id="is_subscribed"
                        <?php if($this->getFormData()->getIsSubscribed()): ?>
                            checked="checked"
                        <?php endif; ?> />
                    <label for="is_subscribed"><?php echo $this->__('Sign Up for Newsletter') ?></label>
                </li>
            <?php endif; ?>
        </ul>

        <?php echo $this->getChildHtml('persistent.remember.me'); ?>
        <?php echo $this->getChildHtml('persistent.remember.me.tooltip'); ?>

        <button type="submit" title="<?php echo $this->__('Submit') ?>" class="button"><span><?php echo $this->__('Create Account') ?><span></button>
    </form>
</article>

<script>
    document.observe('dom:loaded', function() {
        var dataForm = new VarienForm('form-validate', true);
        <?php if($this->getShowAddressFields()) : ?>
            new RegionUpdater('country', 'region', 'region_id', <?php echo $this->helper('directory')->getRegionJson() ?>, undefined, 'zip');
        <?php endif; ?>
    });
</script>