<?php
/**
 * Generic product list template
 *
 * Used for listing products in category, related, upsell, widget etc. instead
 * of having different templates as default.
 *
 * @author Erik Eng <erik@karlssonlord.com>
 *
 */

$_heading = $this->heading ? $this->heading : 'h2';
$_helper  = $this->helper('catalog/output');
?>

<ul class="product-list">
    <?php foreach($this->products as $_product) : ?>
        <li class="product">
            <a href="<?php echo $_product->getProductUrl() ?>"
                title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>"
                class="product-image">
                <img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(256); ?>"
                    alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />
            </a>

            <<?php echo $_heading; ?> class="product-name">
                <a href="<?php echo $_product->getProductUrl() ?>"
                    title="<?php echo $this->stripTags($_product->getName(), null, true) ?>">
                    <?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></a>
            </<?php echo $_heading; ?>>
            <?php echo $this->getPriceHtml($_product, true) ?>

            <?php if($this->helper('wishlist')->isAllow()) : ?>
                <a href="<?php echo $this->getAddToWishlistUrl($_product) ?>" class="link-wishlist"><?php echo $this->__('Add to Wishlist') ?></a>
            <?php endif; ?>
        </li>
    <?php endforeach; ?>
</ul>