<article class="account-create">
    <header class="page-title">
        <h1><?php echo $this->__('Create an Account') ?></h1>
    </header>

    <?php echo $this->getChildHtml('form_fields_before')?>

    <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>

    <form action="<?php echo $this->getPostActionUrl() ?>" method="post" id="form-validate">
        <h2 class="legend"><?php echo $this->__('Personal Information') ?></h2>
        <input type="hidden" name="success_url" value="<?php echo $this->getSuccessUrl() ?>" />
        <input type="hidden" name="error_url" value="<?php echo $this->getErrorUrl() ?>" />
        <?php echo $this->getLayout()->createBlock('customer/widget_name')->setObject($this->getFormData())->setForceUseCustomerAttributes(true)->toHtml() ?>

        <label for="email_address" class="required"><?php echo $this->__('Email Address') ?> <em>*</em></label>
        <input type="email" name="email" id="email_address" value="<?php echo $this->htmlEscape($this->getFormData()->getEmail()) ?>" title="<?php echo $this->__('Email Address') ?>" class="input-text validate-email required-entry" />

        <?php if ($this->isNewsletterEnabled()): ?>
            <label for="is_subscribed"><input type="checkbox" name="is_subscribed" title="<?php echo $this->__('Sign Up for Newsletter') ?>" value="1" id="is_subscribed"<?php if($this->getFormData()->getIsSubscribed()): ?> checked="checked"<?php endif; ?> class="checkbox" /> <?php echo $this->__('Sign Up for Newsletter') ?></label>
        <?php endif ?>

        <?php $_dob = $this->getLayout()->createBlock('customer/widget_dob') ?>
        <?php if ($_dob->isEnabled()): ?>
            <p><?php echo $_dob->setDate($this->getFormData()->getDob())->toHtml() ?></p>
        <?php endif ?>

        <?php $_taxvat = $this->getLayout()->createBlock('customer/widget_taxvat') ?>
        <?php if ($_taxvat->isEnabled()): ?>
            <p><?php echo $_taxvat->setTaxvat($this->getFormData()->getTaxvat())->toHtml() ?></p>
        <?php endif ?>

        <?php $_gender = $this->getLayout()->createBlock('customer/widget_gender') ?>
        <?php if ($_gender->isEnabled()): ?>
            <p><?php echo $_gender->setGender($this->getFormData()->getGender())->toHtml() ?></p>
        <?php endif ?>

        <?php if($this->getShowAddressFields()): ?>
            <h2><?php echo $this->__('Address Information') ?></h2>

            <label for="company"><?php echo $this->__('Company') ?></label>
            <input type="text" name="company" id="company" value="<?php echo $this->htmlEscape($this->getFormData()->getCompany()) ?>" title="<?php echo $this->__('Company') ?>" class="input-text" />

            <label for="telephone" class="required"><?php echo $this->__('Telephone') ?> <em>*</em></label>
            <input type="text" name="telephone" id="telephone" value="<?php echo $this->htmlEscape($this->getFormData()->getTelephone()) ?>" title="<?php echo $this->__('Telephone') ?>" class="input-text required-entry" />

            <label for="street_1" class="required"><?php echo $this->__('Street Address') ?> <em>*</em></label>
            <input type="text" name="street[]" value="<?php echo $this->htmlEscape($this->getFormData()->getStreet(1)) ?>" title="<?php echo $this->__('Street Address') ?>" id="street_1" class="input-text required-entry" />

            <?php for ($_i=2, $_n=$this->helper('customer/address')->getStreetLines(); $_i<=$_n; $_i++): ?>
                <input type="text" name="street[]" value="<?php echo $this->htmlEscape($this->getFormData()->getStreet($_i)) ?>" title="<?php echo $this->__('Street Address %s', $_i) ?>" id="street_<?php echo $_i?>" class="input-text" />
            <?php endfor ?>

            <label for="city" class="required"><?php echo $this->__('City') ?> <em>*</em></label>
            <input type="text" name="city" value="<?php echo $this->htmlEscape($this->getFormData()->getCity()) ?>" title="<?php echo $this->__('City') ?>" class="input-text required-entry" id="city" />

            <label for="region_id" class="required"><?php echo $this->__('State/Province') ?> <em>*</em></label>
            <select id="region_id" name="region_id" title="<?php echo $this->__('State/Province') ?>" class="validate-select" style="display:none;">
                <option value=""><?php echo $this->__('Please select region, state or province') ?></option>
            </select>
            <script>
                $('region_id').setAttribute('defaultValue', "<?php echo $this->getFormData()->getRegionId() ?>");
            </script>
            <input type="text" id="region" name="region" value="<?php echo $this->htmlEscape($this->getRegion()) ?>" title="<?php echo $this->__('State/Province') ?>" class="input-text" style="display:none;" />

            <label for="zip" class="required"><?php echo $this->__('Zip/Postal Code') ?> <em>*</em></label>
            <input type="text" name="postcode" value="<?php echo $this->htmlEscape($this->getFormData()->getPostcode()) ?>" title="<?php echo $this->__('Zip/Postal Code') ?>" id="zip" class="input-text validate-zip-international required-entry" />

            <label for="country" class="required"><?php echo $this->__('Country') ?> <em>*</em></label>
            <?php echo $this->getCountryHtmlSelect() ?>
            <input type="hidden" name="create_address" value="1" />
            <input type="hidden" name="default_billing" value="1" />
            <input type="hidden" name="default_shipping" value="1" />
        <?php endif; ?>

        <h2 class="legend"><?php echo $this->__('Login Information') ?></h2>
        <label for="password" class="required"><?php echo $this->__('Password') ?> <em>*</em></label>
        <input type="password" name="password" id="password" title="<?php echo $this->__('Password') ?>" class="input-text required-entry validate-password" />

        <label for="confirmation" class="required"><?php echo $this->__('Confirm Password') ?> <em>*</em></label>
        <input type="password" name="confirmation" title="<?php echo $this->__('Confirm Password') ?>" id="confirmation" class="input-text required-entry validate-cpassword" />

        <?php echo $this->getChildHtml('persistent.remember.me'); ?>
        <?php echo $this->getChildHtml('persistent.remember.me.tooltip'); ?>

        <p class="actions">
            <button type="submit" title="<?php echo $this->__('Submit') ?>" class="button"><span><?php echo $this->__('Register account') ?><span></button>
            <a href="<?php echo $this->escapeUrl($this->getBackUrl()) ?>" class="back-link"><?php echo $this->__('Back') ?></a>
        </p>
    </form>
</article>

<script>
    document.observe('dom:loaded', function() {
        var dataForm = new VarienForm('form-validate', true);
        <?php if($this->getShowAddressFields()) : ?>
            new RegionUpdater('country', 'region', 'region_id', <?php echo $this->helper('directory')->getRegionJson() ?>, undefined, 'zip');
        <?php endif; ?>
    });
</script>