<?php
/**
 * Temlate for Mage_Customer_Block_Address_Book block
 * @var $test Mage_Customer_Block_Address_Book
 *
 */
?>
<div class="page-title title-buttons">
    <h1><?php echo $this->__('Address Book') ?></h1>
    <a href="<?php echo $this->getAddAddressUrl() ?>" class="button" title="<?php echo $this->__('Add New Address') ?>"><span><?php echo $this->__('Add New Address') ?></span></a>
</div>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<div class="col2-set addresses-list">
    <div class="col-1 addresses-primary">
        <h2 class="sub-title"><?php echo $this->__('Default Addresses') ?></h2>
        <ol>
            <?php if($_pAddsses = Mage::getSingleton('customer/session')->getCustomer()->getDefaultBilling()): ?>
                <li class="info-box">
                    <h3 class="box-title"><?php echo $this->__('Default Billing Address') ?></h3>
                    <address class="box-content">
                        <?php echo $this->getAddressHtml(Mage::getSingleton('customer/session')->getCustomer()->getAddressById($_pAddsses)) ?>
                    </address>
                    <p class="actions">
                        <a href="<?php echo $this->getAddressEditUrl(Mage::getSingleton('customer/session')->getCustomer()->getAddressById($_pAddsses)) ?>"><?php echo $this->__('Change Billing Address') ?></a>
                    </p>
               </li>
            <?php else: ?>
                <li class="info-box">
                    <h3 class="box-title"><?php echo $this->__('Default Billing Address') ?></h3>
                    <p class="box-content"><?php echo $this->__('You have no default billing address in your address book.') ?></p>
                </li>
            <?php endif ?>

            <?php if($_pAddsses = Mage::getSingleton('customer/session')->getCustomer()->getDefaultShipping()): ?>
                <li class="info-box">
                    <h3 class="box-title"><?php echo $this->__('Default Shipping Address') ?></h3>
                    <address class="box-content">
                        <?php echo $this->getAddressHtml(Mage::getSingleton('customer/session')->getCustomer()->getAddressById($_pAddsses)) ?>
                    </address>
                    <p class="actions">
                        <a href="<?php echo $this->getAddressEditUrl(Mage::getSingleton('customer/session')->getCustomer()->getAddressById($_pAddsses)) ?>"><?php echo $this->__('Change Shipping Address') ?></a>
                    </p>
                </li>
            <?php else: ?>
                <li class="info-box">
                    <h3 class="box-title"><?php echo $this->__('Default Shipping Address') ?></h3>
                    <p class="box-content"><?php echo $this->__('You have no default shipping address in your address book.') ?></p>
                </li>
            <?php endif ?>
        </ol>
    </div>

    <?php if($_pAddsses = $this->getAdditionalAddresses()): ?>
        <h2 class="sub-title"><?php echo $this->__('Additional Address Entries') ?></h2>
        <ol>
            <?php foreach($_pAddsses as $_address): ?>
                <li class="item">
                    <address>
                        <?php echo $this->getAddressHtml($_address) ?><br />
                    </address>
                    <p class="actions">
                        <a href="<?php echo $this->getUrl('customer/address/edit', array('id'=>$_address->getId())) ?>"><?php echo $this->__('Edit Address') ?></a>
                        <a href="<?php echo $this->getDeleteUrl(), 'id/', $_address->getId(); ?>"><?php echo $this->__('Delete Address') ?></a>
                    </p>
                </li>
            <?php endforeach; ?>
        </ol>
    <?php endif; ?>
</div>
<div class="buttons-set">
    <p class="back-link"><a href="<?php echo $this->escapeUrl($this->getBackUrl()) ?>"><small>&laquo; </small><?php echo $this->__('Back') ?></a></p>
</div>