<div class="discount">
    <h2><?php echo $this->__('Discount Codes') ?></h2>
    <form id="discount-coupon-form" action="<?php echo $this->getUrl('checkout/cart/couponPost') ?>" method="post">
        <label for="coupon_code"><?php echo $this->__('Enter your coupon code if you have one.') ?></label>
        <input type="hidden" name="remove" id="remove-coupon" value="0" />
        <input class="input-text"
            id="coupon_code"
            name="coupon_code"
            value="<?php echo $this->htmlEscape($this->getCouponCode()) ?>" />
        <button type="button"
            class="button"
            id="discountFormSubmitButton"
            value="<?php echo $this->__('Apply Coupon') ?>"><span><?php echo $this->__('Apply Coupon') ?></span></button>
        <?php if(strlen($this->getCouponCode())): ?>
            <button type="button"
                class="button cancel-btn"
                id="discountFormCancelButton"
                value="<?php echo $this->__('Cancel Coupon') ?>"><span><?php echo $this->__('Cancel Coupon') ?></span></button>
        <?php endif; ?>
    </form>
    <script>
        document.observe('dom:loaded', function() {
            var discountForm = new VarienForm('discount-coupon-form');
            discountForm.submit = function (isRemove) {
                if (isRemove) {
                    $('coupon_code').removeClassName('required-entry');
                    $('remove-coupon').value = "1";
                } else {
                    $('coupon_code').addClassName('required-entry');
                    $('remove-coupon').value = "0";
                }
                return VarienForm.prototype.submit.bind(discountForm)();
            }

            if($('discountFormSubmitButton')) {
                $('discountFormSubmitButton').observe('click', function(event) {
                    discountForm.submit(false);
                });
            }
            if($('discountFormCancelButton')) {
                $('discountFormCancelButton').observe('click', function(event) {
                    discountForm.submit(true);
                });
            }
        });
    </script>
</div>