<div class="page-title title-buttons">
    <h1><?php echo $this->__('Compare Products') ?></h1>
</div>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<?php if($_total = $this->getItems()->getSize()) : ?>
    <table class="data-table" id="product_comparison">
        <?php $_i=0; foreach($this->getItems() as $_item): ?>
            <?php if($_i++%10==0): ?>
                <col width="1" />
            <?php endif; ?>
            <col width="<?php echo floor(100/$_total); ?>%" />
        <?php endforeach; ?>
        <?php if($_total > 2) : ?>
            <thead>
                <tr>
                    <?php $_i = 0; foreach($this->getItems() as $_item): ?>
                        <?php if($_i++%10==0): ?>
                            <th>&nbsp;</th>
                        <?php endif; ?>
                        <td class="a-right">
                            <a href="<?php echo $this->helper('catalog/product_compare')->getRemoveUrl($_item) ?>"
                                title="<?php echo $this->__('Remove Product') ?>">
                                <?php echo $this->__('Remove Product') ?></a>
                        </td>
                    <?php endforeach; ?>
                </tr>
            </thead>
        <?php endif ?>
        <tbody>
            <tr>
                <?php $_helper = $this->helper('catalog/output'); ?>
                <?php $_i = 0; foreach($this->getItems() as $_item): ?>
                    <?php if($_i++%10==0): ?>
                        <th class="label">&nbsp;</th>
                    <?php endif; ?>
                    <td>
                        <a class="product-image"
                            href="<?php echo $_item->getProductUrl() ?>"
                            title="<?php echo $this->stripTags($_item->getName(), null, true) ?>">
                            <img src="<?php echo $this->helper('catalog/image')->init($_item, 'small_image')->resize(256); ?>"
                                alt="<?php echo $this->stripTags($_item->getName(), null, true) ?>" />
                        </a>
                        <h2 class="product-name">
                            <a href="<?php echo $_item->getProductUrl() ?>"
                                title="<?php echo $this->stripTags($_item->getName(), null, true) ?>">
                                <?php echo $_helper->productAttribute($_item, $_item->getName(), 'name') ?>
                            </a>
                        </h2>
                        <?php echo $this->getPriceHtml($_item, true, '-compare-list-top'); ?>
                        <?php if($_item->isSaleable()) : ?>
                            <a href="<?php echo $this->helper('catalog/product_compare')->getAddToCartUrl($_item) ?>"
                                class="button"
                                title="<?php echo $this->__('Add to Cart') ?>"><span><?php echo $this->__('Add to Cart') ?></span></a>
                        <?php else : ?>
                            <?php if($_item->getIsSalable()): ?>
                                <p class="availability in-stock"><span><?php echo $this->__('In stock') ?></span></p>
                            <?php else : ?>
                                <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
                            <?php endif; ?>
                        <?php endif; ?>
                        <?php if ($this->helper('wishlist')->isAllow()) : ?>
                            <p><a href="<?php echo $this->helper('catalog/product_compare')->getAddToWishlistUrl($_item) ?>" onclick="setPLocation(this.href, true); return false;" class="link-wishlist"><?php echo $this->__('Add to Wishlist') ?></a></p>
                        <?php endif; ?>
                    </td>
                <?php endforeach; ?>
            </tr>
        </tbody>
        <tbody>
            <?php foreach ($this->getAttributes() as $_attribute): ?>
                <tr>
                    <?php $_i = 0 ?>
                    <?php foreach($this->getItems() as $_item): ?>
                    <?php if($_i++%10==0): ?>
                    <th class="label"><span class="nobr"><?php echo $_attribute->getStoreLabel() ? $_attribute->getStoreLabel() : $this->__($_attribute->getFrontendLabel()) ?></span></th>
                    <?php endif; ?>
                    <td>
                        <?php switch ($_attribute->getAttributeCode()) {
                            case "price": ?>
                                <?php echo $this->getPriceHtml($_item, true, '-compare-list-' . $_attribute->getCode()) ?>
                                <?php break;
                            case "small_image": ?>
                                <img src="<?php echo $this->helper('catalog/image')->init($_item, 'small_image')->resize(125, 125); ?>" width="125" height="125" alt="<?php echo $this->stripTags($_item->getName(), null, true) ?>" />
                                <?php break;
                            default: ?>
                                <div class="std">
                                    <?php echo $_helper->productAttribute($_item, $this->getProductAttributeValue($_item, $_attribute), $_attribute->getAttributeCode()) ?>
                                </div>
                                <?php break;
                        } ?>
                    </td>
                    <?php endforeach; ?>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
    <script>
        /**
         * Send remove item request, after that reload windows
         */
        function removeItem(url)
        {
            new Ajax.Request(url, {
                parameters: {isAjax: 1, method: 'POST'},
                onLoading: function(){$('compare-list-please-wait').show();},
                onSuccess: function(transport) {
                    $('compare-list-please-wait').hide();
                    window.location.reload();
                    window.opener.location.reload();
                }
            });
        }
    </script>
<?php endif; ?>