<?php
/**
 * @var $this Mage_Catalog_Block_Product_Compare_Sidebar
 *
 */

$_helper = $this->helper('catalog/product_compare');
$_items = $_helper->getItemCount() > 0 ? $_helper->getItemCollection() : null;
if($_helper->getItemCount() > 0) : ?>
    <div class="block block-list block-compare">
        <div class="block-title">
            <h3><?php echo $this->__('Compare Products') ?></h3>
        </div>
        <div class="block-content">
            <ol id="compare-items">
                <?php foreach($_items as $_index => $_item) : ?>
                    <li class="item">
                        <input type="hidden" class="compare-item-id" value="<?php echo $_item->getId() ?>" />
                        <a class="product-name"
                            href="<?php echo $this->getProductUrl($_item) ?>"><?php echo $this->helper('catalog/output')->productAttribute($_item, $_item->getName(), 'name') ?></a>
                        <a href="<?php echo $_helper->getRemoveUrl($_item) ?>"
                            title="<?php echo $this->__('Remove This Item') ?>"
                            class="btn-remove"><span><?php echo $this->__('Remove This Item') ?></span></a>
                    </li>
                <?php endforeach; ?>
            </ol>
            <div class="actions">
                <a href="<?php echo $this->helper('catalog/product_compare')->getListUrl(); ?>"
                    title="<?php echo $this->__('Compare') ?>"
                    class="button"><span><?php echo $this->__('Compare') ?></span></a>
                <a href="<?php echo $_helper->getClearListUrl() ?>"><?php echo $this->__('Clear All') ?></a>
            </div>
        </div>
    </div>
<?php endif; ?>