<?php if (!Mage::helper('core/cookie')->isUserNotAllowSaveCookie()): ?>
    <?php $accountId = Mage::getStoreConfig(Mage_GoogleAnalytics_Helper_Data::XML_PATH_ACCOUNT) ?>
    <script>
        var _gaq = [];
        <?php echo $this->_getPageTrackingCode($accountId) ?>
        (function(d, t) {
            var g = d.createElement(t),
                s = d.getElementsByTagName(t)[0];
            g.src = '//www.google-analytics.com/ga.js';
            s.parentNode.insertBefore(g, s);
        }(document, 'script'));
        <?php echo $this->_getOrdersTrackingCode() ?>
    </script>
<?php endif; ?>