<div class="page-title">
    <h1><?php echo $this->__('Edit Account Information') ?></h1>
</div>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<form action="<?php echo $this->getUrl('customer/account/editPost') ?>" method="post" id="form-validate" enctype="multipart/form-data">
    <?php echo $this->getBlockHtml('formkey'); ?>
    <?php echo $this->getLayout()->createBlock('customer/widget_name')->setObject($this->getCustomer())->toHtml() ?>
    <label for="email" class="required"><?php echo $this->__('Email Address') ?> <em>*</em></label>
    <input type="text" name="email" id="email" value="<?php echo $this->htmlEscape($this->getCustomer()->getEmail()) ?>" title="<?php echo $this->__('Email Address') ?>" class="input-text required-entry validate-email" />
    <?php
    $_dob    = $this->getLayout()->createBlock('customer/widget_dob');
    $_taxvat = $this->getLayout()->createBlock('customer/widget_taxvat');
    $_gender = $this->getLayout()->createBlock('customer/widget_gender'); ?>
    <?php if($_dob->isEnabled() || $_taxvat->isEnabled() || $_gender->isEnabled()) : ?>
        <?php if ($_dob->isEnabled()): ?>
            <?php echo $_dob->setDate($this->getCustomer()->getDob())->toHtml() ?>
        <?php endif ?>
        <?php if ($_taxvat->isEnabled()): ?>
            <?php echo $_taxvat->setTaxvat($this->getCustomer()->getTaxvat())->toHtml() ?>
        <?php endif ?>
        <?php if ($_gender->isEnabled()): ?>
            <?php echo $_gender->setGender($this->getCustomer()->getGender())->toHtml() ?>
        <?php endif ?>
    <?php endif; ?>
    <label for="change_password">
        <input type="checkbox" name="change_password" id="change_password" value="1" title="<?php echo $this->__('Change Password') ?>"<?php if($this->getCustomer()->getChangePassword()==1): ?> checked="checked"<?php endif; ?> class="checkbox" />
        <?php echo $this->__('Change Password') ?>
    </label>
    <?php $userDefinedAttributes = $this->getLayout()->getBlock('customer_form_user_attributes'); ?>
    <?php if($userDefinedAttributes) : ?>
        <?php echo $userDefinedAttributes->setEntity($this->getCustomer())->toHtml(); ?>
    <?php endif; ?>
    <div style="display:none;">
        <h2 class="legend"><?php echo $this->__('Change Password') ?></h2>

        <label for="current_password"><?php echo $this->__('Current Password') ?></label>
        <input type="password" class="input-text" name="current_password" id="current_password" />

        <label for="password"><?php echo $this->__('New Password') ?></label>
        <input type="password" class="input-text validate-password" name="password" id="password" />

        <label for="confirmation"><?php echo $this->__('Confirm New Password') ?></label>
        <input type="password" class="input-text validate-cpassword" name="confirmation" id="confirmation" />
    </div>
    <p>
        <button type="submit" class="button" title="<?php echo $this->__('Save') ?>"><span><?php echo $this->__('Save') ?></span></button>
        <?php echo $this->__('or'); ?>
        <a href="<?php echo $this->escapeUrl($this->getBackUrl()) ?>"><?php echo $this->__('Go back') ?></a>
    </p>
</form>
<script>
    document.observe('dom:loaded', function() {
        var dataForm = new VarienForm('form-validate', true);
        function setPasswordForm(arg){
            if(arg){
                $('current_password').up().show();
                $('current_password').addClassName('required-entry');
                $('password').addClassName('required-entry');
                $('confirmation').addClassName('required-entry');

            }else{
                $('current_password').up().hide();
                $('current_password').removeClassName('required-entry');
                $('password').removeClassName('required-entry');
                $('confirmation').removeClassName('required-entry');
            }
        }
        <?php if($this->getCustomer()->getChangePassword()): ?>
            setPasswordForm(true);
        <?php endif; ?>

        if($('change_password')) {
            $('change_password').observe('click', function(event) {
                setPasswordForm(this.checked);
            });
        }
    });
</script>